# Initial data by /r/AnduCrandu
# Python conversion and revisions by /r/Meteorchestra

heroList = {
	"Alfonse":{
		"bases":{"hp":19, "atk":9, "spd":6, "def":8, "res":5},
		"growths":{"hp":7, "atk":8, "spd":5, "def":7, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":2,
			"Steel Sword":2,
			"Silver Sword":3,
			"Folkvangr":5,
			"Daylight":2,
			"Sol":4,
			"Death Blow 1":2,
			"Death Blow 2":2,
			"Death Blow 3":4,
			"Spur Atk 1":3,
			"Spur Atk 2":4,
			"Spur Atk 3":5
		},
	},
	"Caeda":{
		"bases":{"hp":17, "atk":6, "spd":9, "def":5, "res":10},
		"growths":{"hp":5, "atk":5, "spd":9, "def":5, "res":7},
		"color":"red",
		"weapontype":"sword",
		"movetype":"flying",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Armorslayer":4,
			"Armorslayer+":5,
			"Darting Blow 1":4,
			"Darting Blow 2":4,
			"Darting Blow 3":5,
			"Fortify Res 1":4,
			"Fortify Res 2":4,
			"Fortify Fliers":4
		},
	},
	"Cain":{
		"bases":{"hp":18, "atk":8, "spd":6, "def":8, "res":6},
		"growths":{"hp":7, "atk":7, "spd":8, "def":5, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Brave Sword":4,
			"Brave Sword+":5,
			"Buckler":4,
			"Escutcheon":4,
			"Wings of Mercy 1":4,
			"Wings of Mercy 2":4,
			"Wings of Mercy 3":4,
			"Threaten Atk 1":4,
			"Threaten Atk 2":4,
			"Threaten Atk 3":5,
		},
	},
	"Chrom":{
		"bases":{"hp":21, "atk":9, "spd":6, "def":8, "res":6},
		"growths":{"hp":8, "atk":9, "spd":5, "def":7, "res":2},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Falchion":5,
			"Daylight":4,
			"Sol":4,
			"Aether":5,
			"Defiant Def 1":4,
			"Defiant Def 2":4,
			"Defiant Def 3":4,
			"Spur Def 1":4,
			"Spur Def 2":4,
			"Spur Def 3":5
		},
	},
	"Corrin(M)":{
		"bases":{"hp":20, "atk":8, "spd":8, "def":6, "res":5},
		"growths":{"hp":6, "atk":7, "spd":7, "def":6, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Yato":5,
			"Dragon Gaze":4,
			"Dragon Fang":4,
			"Defense 1":4,
			"Defense 2":4,
			"Defense 3":4,
			"Obstruct 1":4,
			"Obstruct 2":4,
			"Obstruct 3":5
		},
	},
	"Draug":{
		"bases":{"hp":24, "atk":8, "spd":6, "def":13, "res":3},
		"growths":{"hp":8, "atk":6, "spd":8, "def":8, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"armored",
		"skills":{
			"Iron Sword":2,
			"Steel Sword":2,
			"Brave Sword":3,
			"Brave Sword+":5,
			"Buckler":3,
			"Pavise":4,
			"Lunge":3,
			"Spur Def 1":2,
			"Spur Def 2":2,
			"Ward Armor":4
		},
	},
	"Eirika":{
		"bases":{"hp":18, "atk":7, "spd":9, "def":7, "res":6},
		"growths":{"hp":7, "atk":5, "spd":8, "def":5, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Sieglinde":5,
			"Drag Back":4,
			"Hone Spd 1":4,
			"Hone Spd 2":4,
			"Hone Spd 3":4
		},
	},
	"Eldigan":{
		"bases":{"hp":19, "atk":8, "spd":5, "def":8, "res":6},
		"growths":{"hp":8, "atk":7, "spd":5, "def":8, "res":2},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Killing Edge":5,
			"Mystletainn":5,
			"Rising Light":5,
			"Growing Light":5,
			"Fury 1":5,
			"Fury 2":5,
			"Fury 3":5,
			"Lunge":5
		},
	},
	"Eliwood":{
		"bases":{"hp":17, "atk":7, "spd":8, "def":6, "res":8},
		"growths":{"hp":6, "atk":7, "spd":6, "def":4, "res":7},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Silver Sword":3,
			"Durandal":5,
			"Holy Vestments":3,
			"Sacred Cowl":4,
			"Axebreaker 1":3,
			"Axebreaker 2":4,
			"Axebreaker 3":5,
			"Spur Res 1":3,
			"Spur Res 2":3,
			"Ward Cavalry":4
		},
	},
	"Fir":{
		"bases":{"hp":19, "atk":6, "spd":10, "def":5, "res":7},
		"growths":{"hp":6, "atk":5, "spd":8, "def":5, "res":7},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Killing Edge":3,
			"Killing Edge+":5,
			"Chilling Wind":3,
			"Glacies":4,
			"Speed 1":3,
			"Speed 2":3,
			"Speed 3":4,
			"Pass 1":3,
			"Pass 2":4,
			"Pass 3":5
		},
	},
	"Hana":{
		"bases":{"hp":18, "atk":9, "spd":10, "def":6, "res":4},
		"growths":{"hp":5, "atk":8, "spd":8, "def":4, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":1,
			"Steel Sword":2,
			"Armorslayer":3,
			"Armorslayer+":5,
			"Life and Death 1":3,
			"Life and Death 2":4,
			"Life and Death 3":5,
			"Obstruct 1":1,
			"Obstruct 2":2,
			"Obstruct 3":4
		},
	},
	"Henry":{
		"bases":{"hp":19, "atk":6, "spd":5, "def":8, "res":6},
		"growths":{"hp":8, "atk":4, "spd":4, "def":7, "res":5},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Flux":3,
			"Ruin":3,
			"Raudrraven":3,
			"Raudrraven+":5,
			"Glowing Ember":3,
			"Ignis":4,
			"Defiant Def 1":3,
			"Defiant Def 2":4,
			"Defiant Def 3":5,
			"G Tomebreaker 1":3,
			"G Tomebreaker 2":3,
			"G Tomebreaker 3":4
		},
	},
	"Hinata":{
		"bases":{"hp":21, "atk":8, "spd":5, "def":10, "res":3},
		"growths":{"hp":8, "atk":7, "spd":5, "def":8, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":1,
			"Steel Sword":2,
			"Ruby Sword":3,
			"Ruby Sword+":5,
			"Buckler":3,
			"Pavise":4,
			"Fury 1":1,
			"Fury 2":2,
			"Fury 3":4,
			"Brash Assault 1":3,
			"Brash Assault 2":4,
			"Brash Assault 3":5
		},
	},
	"Karel":{
		"bases":{"hp":19, "atk":8, "spd":9, "def":6, "res":5},
		"growths":{"hp":9, "atk":6, "spd":8, "def":6, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Wo Dao":5,
			"Wo Dao+":5,
			"Retribution":5,
			"Reprisal":5,
			"Defiant Atk 1":5,
			"Defiant Atk 2":5,
			"Defiant Atk 3":5,
			"Desperation 1":5,
			"Desperation 2":5,
			"Desperation 3":5
		},
	},
	"Laslow":{
		"bases":{"hp":20, "atk":9, "spd":7, "def":6, "res":5},
		"growths":{"hp":7, "atk":8, "spd":5, "def":7, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Silver Sword":3,
			"Silver Sword+":5,
			"Daylight":3,
			"Noontime":4,
			"Axebreaker 1":3,
			"Axebreaker 2":3,
			"Axebreaker 3":4,
			"Hone Spd 1":3,
			"Hone Spd 2":4,
			"Hone Spd 3":5
		},
	},
	"Leo":{
		"bases":{"hp":17, "atk":7, "spd":5, "def":6, "res":8},
		"growths":{"hp":6, "atk":6, "spd":4, "def":5, "res":6},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"cavalry",
		"skills":{
			"Flux":5,
			"Ruin":5,
			"Fenrir":5,
			"Brynhildr":5,
			"Rising Light":5,
			"Blazing Light":5,
			"Quick Riposte 1":5,
			"Quick Riposte 2":5,
			"Quick Riposte 3":5,
			"Savage Blow 1":5,
			"Savage Blow 2":5,
			"Savage Blow 3":5
		},
	},
	"Lilina":{
		"bases":{"hp":16, "atk":9, "spd":6, "def":4, "res":9},
		"growths":{"hp":5, "atk":9, "spd":5, "def":3, "res":6},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Fire":4,
			"Elfire":4,
			"Bolganone":4,
			"Bolganone+":5,
			"Rising Flame":4,
			"Growing Flame":4,
			"Attack 1":4,
			"Attack 2":4,
			"Attack 3":5,
			"Spur Atk 1":4,
			"Spur Atk 2": 4,
			"Spur Atk 3": 4
		},
	},
	"Lon'qu":{
		"bases":{"hp":19, "atk":7, "spd":11, "def":5, "res":5},
		"growths":{"hp":8, "atk":6, "spd":9, "def":4, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Killing Edge":3,
			"Killing Edge+":5,
			"Night Sky":3,
			"Glimmer":4,
			"Speed 1":3,
			"Speed 2":4,
			"Speed 3":5,
			"Vantage 1":3,
			"Vantage 2":3,
			"Vantage 3":4
		},
	},
	"Lucina":{
		"bases":{"hp":19, "atk":8, "spd":10, "def":6, "res":4},
		"growths":{"hp":7, "atk":8, "spd":8, "def":5, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Silver Sword":5,
			"Falchion":5,
			"New Moon":5,
			"Luna":5,
			"Aether":5,
			"Defiant Spd 1":5,
			"Defiant Spd 2":5,
			"Defiant Spd 3":5,
			"Spur Atk 1":5,
			"Spur Atk 2":5,
			"Spur Atk 3":5
		},
	},
	"Lyn":{
		"bases":{"hp":18, "atk":6, "spd":11, "def":7, "res":5},
		"growths":{"hp":5, "atk":6, "spd":8, "def":5, "res":7},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Silver Sword":5,
			"Sol Katti":5,
			"Night Sky":5,
			"Astra":5,
			"Galeforce":5,
			"Defiant Atk 1":5,
			"Defiant Atk 2":5,
			"Defiant Atk 3":5,
			"Spur Spd 1":5,
			"Spur Spd 2":5,
			"Spur Spd 3":5
		},
	},
	"Marth":{
		"bases":{"hp":19, "atk":7, "spd":8, "def":7, "res":6},
		"growths":{"hp":6, "atk":7, "spd":8, "def":6, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Falchion":5,
			"Escape Route 1":4,
			"Escape Route 2":4,
			"Escape Route 3":5,
			"Spur Spd 1":4,
			"Spur Spd 2":4,
			"Spur Spd 3":4
		},
	},
	"Ogma":{
		"bases":{"hp":21, "atk":7, "spd":10, "def":6, "res":3},
		"growths":{"hp":8, "atk":9, "spd":7, "def":6, "res":1},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Brave Sword":4,
			"Brave Sword+":5,
			"Daylight":4,
			"Noontime":4,
			"Defiant Atk 1":4,
			"Defiant Atk 2":4,
			"Defiant Atk 3":4,
			"Spur Atk 1":4,
			"Spur Atk 2":4,
			"Spur Atk 3":5
		},
	},
	"Olivia":{
		"bases":{"hp":17, "atk":6, "spd":7, "def":5, "res":4},
		"growths":{"hp":5, "atk":6, "spd":8, "def":6, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":1,
			"Steel Sword":2,
			"Silver Sword":3,
			"Silver Sword+":5,
			"Knock Back":3,
			"Hone Atk 1":1,
			"Hone Atk 2":2,
			"Hone Atk 3":4
		},
	},
	"Palla":{
		"bases":{"hp":18, "atk":7, "spd":9, "def":6, "res":7},
		"growths":{"hp":7, "atk":7, "spd":6, "def":6, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"flying",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Ruby Sword":3,
			"Ruby Sword+":5,
			"New Moon":3,
			"Moonbow":4,
			"Wings of Mercy 1":3,
			"Wings of Mercy 2":4,
			"Wings of Mercy 3":5,
			"Spur Spd 1":3,
			"Spur Spd 2":3,
			"Goad Fliers":4
		},
	},
	"Raigh":{
		"bases":{"hp":17, "atk":8, "spd":7, "def":5, "res":7},
		"growths":{"hp":5, "atk":7, "spd":6, "def":4, "res":6},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Flux":2,
			"Ruin":2,
			"Raudrwolf":3,
			"Raudrwolf+":5,
			"HP 3":3,
			"HP 4":4,
			"HP 5":5,
			"Seal Res 1":2,
			"Seal Res 2":2,
			"Seal Res 3":4
		},
	},
	"Roy":{
		"bases":{"hp":20, "atk":8, "spd":9, "def":6, "res":4},
		"growths":{"hp":7, "atk":6, "spd":6, "def":5, "res":7},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Binding Blade":5,
			"Triangle Adept 1":4,
			"Triangle Adept 2":4,
			"Triangle Adept 3":4,
			"Seal Def 1":4,
			"Seal Def 2":4,
			"Seal Def 3":5
		},
	},
	"Ryoma":{
		"bases":{"hp":19, "atk":8, "spd":11, "def":5, "res":4},
		"growths":{"hp":6, "atk":8, "spd":7, "def":6, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Silver Sword":5,
			"Raijinto":5,
			"Night Sky":5,
			"Astra":5,
			"Defiant Atk 1":5,
			"Defiant Atk 2":5,
			"Defiant Atk 3":5,
			"Hone Spd 1":5,
			"Hone Spd 2":5,
			"Hone Spd 3":5
		},
	},
	"Sanaki":{
		"bases":{"hp":16, "atk":9, "spd":7, "def":4, "res":8},
		"growths":{"hp":4, "atk":9, "spd":5, "def":2, "res":8},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Fire":5,
			"Elfire":5,
			"Bolganone":5,
			"Cymbeline":5,
			"Triangle Adept 1":5,
			"Triangle Adept 2":5,
			"Triangle Adept 3":5,
			"Hone Atk 1":5,
			"Hone Atk 2":5,
			"Hone Atk 3":5
		},
	},
	"Selena":{
		"bases":{"hp":18, "atk":6, "spd":9, "def":8, "res":6},
		"growths":{"hp":5, "atk":5, "spd":8, "def":7, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Armorslayer":3,
			"Armorslayer+":5,
			"Triangle Adept 1":3,
			"Triangle Adept 2":4,
			"Triangle Adept 3":5,
			"Threaten Spd 1":3,
			"Threaten Spd 2":3,
			"Threaten Spd 3":4
		},
	},
	"Seliph":{
		"bases":{"hp":19, "atk":8, "spd":7, "def":8, "res":5},
		"growths":{"hp":9, "atk":8, "spd":4, "def":6, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Tyrfing":5,
			"HP 3":4,
			"HP 4":4,
			"HP 5":4,
			"Brash Assault 1":4,
			"Brash Assault 2":4,
			"Brash Assault 3":5
		},
	},
	"Sophia":{
		"bases":{"hp":18, "atk":9, "spd":4, "def":6, "res":7},
		"growths":{"hp":6, "atk":7, "spd":3, "def":6, "res":6},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Flux":1,
			"Ruin":2,
			"Fenrir":3,
			"Fenrir+":5,
			"Dragon Gaze":3,
			"Dragon Fang":4,
			"Warding Blow 1":3,
			"Warding Blow 2":4,
			"Warding Blow 3":5,
			"Fortify Res 1":1,
			"Fortify Res 2":2,
			"Fortify Res 3":4
		},
	},
	"Stahl":{
		"bases":{"hp":19, "atk":7, "spd":7, "def":8, "res":5},
		"growths":{"hp":8, "atk":7, "spd":5, "def":6, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":1,
			"Steel Sword":2,
			"Ruby Sword":3,
			"Ruby Sword+":5,
			"Defense 1":1,
			"Defense 2":2,
			"Defense 3":4,
			"Obstruct 1":3,
			"Obstruct 2":4,
			"Obstruct 3":5
		},
	},
	"Tharja":{
		"bases":{"hp":17, "atk":8, "spd":8, "def":6, "res":5},
		"growths":{"hp":6, "atk":7, "spd":8, "def":4, "res":3},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Flux":4,
			"Ruin":4,
			"Raudrblade":4,
			"Raudrblade+":5,
			"Retribution":4,
			"Vengeance":4,
			"Darting Blow 1":4,
			"Darting Blow 2":4,
			"Darting Blow 3":4,
			"Spur Res 1":4,
			"Spur Res 2":4,
			"Spur Res 3":5
		},
	},
	"Tiki(A)":{
		"bases":{"hp":18, "atk":7, "spd":6, "def":9, "res":7},
		"growths":{"hp":6, "atk":9, "spd":4, "def":8, "res":4},
		"color":"red",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":3,
			"Fire Breath+":3,
			"Lightning Breath":3,
			"Lightning Breath+":5,
			"Glowing Ember":3,
			"Bonfire":4,
			"Defiant Atk 1":3,
			"Defiant Atk 2":3,
			"Defiant Atk 3":4,
			"Spur Res 1":3,
			"Spur Res 2":4,
			"Spur Res 3":5
		},
	},
	"Tiki(Y)":{
		"bases":{"hp":15, "atk":5, "spd":4, "def":8, "res":7},
		"growths":{"hp":8, "atk":8, "spd":8, "def":7, "res":6},
		"color":"red",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":5,
			"Fire Breath+":5,
			"Flametongue":5,
			"Flametongue+":5,
			"Rising Flame":5,
			"Growing Flame":5,
			"Armored Blow 1":5,
			"Armored Blow 2":5,
			"Armored Blow 3":5,
			"Breath of Life 1":5,
			"Breath of Life 2":5,
			"Breath of Life 3":5
		},
	},
	"Anna":{
		"bases":{"hp":19, "atk":7, "spd":10, "def":5, "res":6},
		"growths":{"hp":6, "atk":6, "spd":9, "def":4, "res":6},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":2,
			"Steel Axe":2,
			"Silver Axe":3,
			"Noatun":5,
			"Night Sky":2,
			"Astra":4,
			"Vantage 1":3,
			"Vantage 2":4,
			"Vantage 3":5,
			"Spur Res 1":2,
			"Spur Res 2":2,
			"Spur Res 3":4
		},
	},
	"Arthur":{
		"bases":{"hp":19, "atk":8, "spd":7, "def":8, "res":5},
		"growths":{"hp":7, "atk":7, "spd":6, "def":6, "res":5},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Emerald Axe":3,
			"Emerald Axe+":5,
			"HP 3":3,
			"HP 4":3,
			"HP 5":4,
			"Lancebreaker 1":3,
			"Lancebreaker 2":4,
			"Lancebreaker 3":5
		},
	},
	"Barst":{
		"bases":{"hp":20, "atk":9, "spd":8, "def":6, "res":4},
		"growths":{"hp":8, "atk":7, "spd":7, "def":7, "res":2},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Brave Axe":3,
			"Brave Axe+":5,
			"Knock Back":3,
			"Spur Atk 1":3,
			"Spur Atk 2":3,
			"Spur Atk 3":4
		},
	},
	"Bartre":{
		"bases":{"hp":21, "atk":10, "spd":6, "def":7, "res":3},
		"growths":{"hp":9, "atk":8, "spd":5, "def":8, "res":1},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Hammer":3,
			"Hammer+":5,
			"Fury 1":3,
			"Fury 2":4,
			"Fury 3":5,
			"Brash Assault 1":3,
			"Brash Assault 2":3,
			"Brash Assault 3":4
		},
	},
	"Beruka":{
		"bases":{"hp":20, "atk":7, "spd":6, "def":9, "res":5},
		"growths":{"hp":8, "atk":6, "spd":4, "def":9, "res":4},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Killer Axe":3,
			"Killer Axe+":5,
			"Night Sky":3,
			"Glimmer":4,
			"Defiant Def 1":3,
			"Defiant Def 2":3,
			"Defiant Def 3":4,
			"Lunge":3
		},
	},
	"Camilla":{
		"bases":{"hp":18, "atk":8, "spd":8, "def":6, "res":7},
		"growths":{"hp":5, "atk":6, "spd":7, "def":6, "res":7},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":4,
			"Steel Axe":4,
			"Brave Axe":4,
			"Brave Axe+":5,
			"Dragon Gaze":4,
			"Draconic Aura":4,
			"Darting Blow 1":4,
			"Darting Blow 2":4,
			"Darting Blow 3":5,
			"Savage Blow 1":4,
			"Savage Blow 2":4,
			"Savage Blow 3":4
		},
	},
	"Cecilia":{
		"bases":{"hp":17, "atk":8, "spd":6, "def":5, "res":7},
		"growths":{"hp":5, "atk":7, "spd":5, "def":4, "res":6},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"cavalry",
		"skills":{
			"Wind":1,
			"Elwind":2,
			"Gronnraven":3,
			"Gronnraven+":5,
			"Attack 1":3,
			"Attack 2":4,
			"Attack 3":5,
			"Escape Route 1":1,
			"Escape Route 2":2,
			"Escape Route 3":4
		},
	},
	"Cherche":{
		"bases":{"hp":20, "atk":10, "spd":6, "def":8, "res":3},
		"growths":{"hp":8, "atk":9, "spd":5, "def":7, "res":2},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Hammer":3,
			"Hammer+":5,
			"Attack 1":3,
			"Attack 2":3,
			"Attack 3":4,
			"Fortify Def 1":3,
			"Fortify Def 2":4,
			"Fortify Def 3":5
		},
	},
	"Fae":{
		"bases":{"hp":16, "atk":5, "spd":4, "def":6, "res":8},
		"growths":{"hp":10, "atk":9, "spd":7, "def":5, "res":6},
		"color":"green",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":4,
			"Fire Breath+":4,
			"Light Breath":4,
			"Light Breath+":5,
			"Renewal 1":4,
			"Renewal 2":4,
			"Renewal 3":5
		},
	},
	"Frederick":{
		"bases":{"hp":19, "atk":9, "spd":6, "def":8, "res":4},
		"growths":{"hp":7, "atk":8, "spd":5, "def":9, "res":1},
		"color":"green",
		"weapontype":"axe",
		"movetype":"cavalry",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Hammer":3,
			"Hammer+":5,
			"New Moon":3,
			"Luna":4,
			"Wings of Mercy 1":3,
			"Wings of Mercy 2":4,
			"Wings of Mercy 3":5,
			"Fortify Def 1":3,
			"Fortify Def 2":3,
			"Fortify Def 3":4
		},
	},
	"Gunter":{
		"bases":{"hp":21, "atk":10, "spd":7, "def":11, "res":5},
		"growths":{"hp":6, "atk":6, "spd":4, "def":6, "res":2},
		"color":"green",
		"weapontype":"axe",
		"movetype":"cavalry",
		"skills":{
			"Iron Axe":1,
			"Steel Axe":2,
			"Silver Axe":3,
			"Silver Axe+":5,
			"Armored Blow 1":3,
			"Armored Blow 2":4,
			"Armored Blow 3":5,
			"Hone Atk 1":1,
			"Hone Atk 2":2,
			"Hone Cavalry":4
		},
	},
	"Hawkeye":{
		"bases":{"hp":21, "atk":9, "spd":5, "def":6, "res":6},
		"growths":{"hp":7, "atk":7, "spd":4, "def":6, "res":7},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":4,
			"Steel Axe":4,
			"Killer Axe":4,
			"Killer Axe+":5,
			"Rising Light":4,
			"Growing Light":4,
			"Death Blow 1":4,
			"Death Blow 2":4,
			"Death Blow 3":5,
			"Threaten Atk 1":4,
			"Threaten Atk 2":4,
			"Threaten Atk 3":4
		},
	},
	"Hector":{
		"bases":{"hp":24, "atk":10, "spd":5, "def":11, "res":4},
		"growths":{"hp":9, "atk":8, "spd":5, "def":8, "res":3},
		"color":"green",
		"weapontype":"axe",
		"movetype":"armored",
		"skills":{
			"Iron Axe":5,
			"Steel Axe":5,
			"Silver Axe":5,
			"Armads":5,
			"Buckler":5,
			"Pavise":5,
			"Distant Counter":5,
			"Spur Atk 1":5,
			"Spur Atk 2":5,
			"Goad Armor":5
		},
	},
	"Julia":{
		"bases":{"hp":16, "atk":9, "spd":7, "def":4, "res":8},
		"growths":{"hp":6, "atk":8, "spd":5, "def":2, "res":7},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":5,
			"Elwind":5,
			"Rexcalibur":5,
			"Naga":5,
			"Dragon Gaze":5,
			"Dragon Fang":5,
			"Resistance 1":5,
			"Resistance 2":5,
			"Resistance 3":5,
			"Breath of Life 1":5,
			"Breath of Life 2":5,
			"Breath of Life 3":5
		},
	},
	"Merric":{
		"bases":{"hp":19, "atk":7, "spd":8, "def":6, "res":4},
		"growths":{"hp":7, "atk":5, "spd":7, "def":6, "res":3},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":4,
			"Elwind":4,
			"Rexcalibur":4,
			"Excalibur":5,
			"Rising Wind":4,
			"Growing Wind":4,
			"HP 3":4,
			"HP 4":4,
			"HP 5":5,
			"Spur Res 1":4,
			"Spur Res 2":4,
			"Spur Res 3":4
		},
	},
	"Minerva":{
		"bases":{"hp":18, "atk":7, "spd":9, "def":8, "res":5},
		"growths":{"hp":6, "atk":7, "spd":7, "def":7, "res":4},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":5,
			"Steel Axe":5,
			"Silver Axe":5,
			"Hauteclere":5,
			"Holy Vestments":5,
			"Sacred Cowl":5,
			"Life and Death 1":5,
			"Life and Death 2":5,
			"Life and Death 3":5,
			"Spur Def 1":5,
			"Spur Def 2":5,
			"Ward Fliers":5
		},
	},
	"Narcian":{
		"bases":{"hp":18, "atk":7, "spd":7, "def":8, "res":7},
		"growths":{"hp":7, "atk":6, "spd":6, "def":7, "res":5},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":2,
			"Steel Axe":2,
			"Emerald Axe":3,
			"Emerald Axe+":5,
			"Retribution":3,
			"Vengeance":4,
			"Lancebreaker 1":2,
			"Lancebreaker 2":2,
			"Lancebreaker 3":4,
			"Savage Blow 1":3,
			"Savage Blow 2":4,
			"Savage Blow 3":5
		},
	},
	"Nino":{
		"bases":{"hp":16, "atk":7, "spd":10, "def":4, "res":7},
		"growths":{"hp":4, "atk":8, "spd":8, "def":3, "res":5},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":3,
			"Elwind":3,
			"Gronnblade":3,
			"Gronnblade+":5,
			"Resistance 1":3,
			"Resistance 2":3,
			"Resistance 3":4,
			"Hone Atk 1":3,
			"Hone Atk 2":4,
			"Hone Atk 3":5
		},
	},
	"Raven":{
		"bases":{"hp":19, "atk":8, "spd":9, "def":6, "res":5},
		"growths":{"hp":6, "atk":8, "spd":8, "def":5, "res":4},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":4,
			"Steel Axe":4,
			"Brave Axe":4,
			"Brave Axe+":5,
			"Daylight":4,
			"Sol":4,
			"Defiant Spd 1":4,
			"Defiant Spd 2":4,
			"Defiant Spd 3":4,
			"Threaten Def 1":4,
			"Threaten Def 2":4,
			"Threaten Def 3":5
		},
	},
	"Robin(F)":{
		"bases":{"hp":18, "atk":7, "spd":7, "def":7, "res":5},
		"growths":{"hp":6, "atk":6, "spd":6, "def":6, "res":4},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":2,
			"Elwind":2,
			"Gronnwolf":3,
			"Gronnwolf+":5,
			"Glowing Ember":3,
			"Ignis":4,
			"Defiant Res 1":3,
			"Defiant Res 2":4,
			"Defiant Res 3":5,
			"B Tomebreaker 1":2,
			"B Tomebreaker 2":3,
			"B Tomebreaker 3":4
		},
	},
	"Sheena":{
		"bases":{"hp":21, "atk":8, "spd":6, "def":12, "res":7},
		"growths":{"hp":7, "atk":6, "spd":5, "def":7, "res":8},
		"color":"green",
		"weapontype":"axe",
		"movetype":"armored",
		"skills":{
			"Iron Axe":4,
			"Steel Axe":4,
			"Killer Axe":4,
			"Killer Axe+":5,
			"Buckler":4,
			"Escutcheon":4,
			"Svalinn Shield":4,
			"Fortify Def 1":4,
			"Fortify Def 2":4,
			"Fortify Armor":4
		},
	},
	"Abel":{
		"bases":{"hp":17, "atk":7, "spd":8, "def":8, "res":6},
		"growths":{"hp":6, "atk":8, "spd":7, "def":4, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Brave Lance":4,
			"Brave Lance+":5,
			"Holy Vestments":4,
			"Aegis":4,
			"HP 3":4,
			"HP 4":4,
			"HP 5":5,
			"Swordbreaker 1":4,
			"Swordbreaker 2":4,
			"Swordbreaker 3":4
		},
	},
	"Azura":{
		"bases":{"hp":17, "atk":5, "spd":7, "def":4, "res":6},
		"growths":{"hp":5, "atk":8, "spd":8, "def":4, "res":6},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"Sapphire Lance":5,
			"Sapphire Lance+":5,
			"Speed 1":5,
			"Speed 2":5,
			"Speed 3":5,
			"Fortify Res 1":5,
			"Fortify Res 2":5,
			"Fortify Res 3":5
		},
	},
	"Catria":{
		"bases":{"hp":17, "atk":7, "spd":10, "def":7, "res":6},
		"growths":{"hp":6, "atk":7, "spd":7, "def":6, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Killer Lance":3,
			"Killer Lance+":5,
			"New Moon":4,
			"Luna":4,
			"Armored Blow 1":4,
			"Armored Blow 2":4,
			"Armored Blow 3":4,
			"Seal Atk 1":4,
			"Seal Atk 2":4,
			"Seal Atk 3":5
		},
	},
	"Cordelia":{
		"bases":{"hp":18, "atk":9, "spd":9, "def":5, "res":6},
		"growths":{"hp":6, "atk":8, "spd":8, "def":4, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Brave Lance":4,
			"Brave Lance+":5,
			"Night Sky":4,
			"Astra":4,
			"Galeforce":5,
			"Triangle Adept 1":4,
			"Triangle Adept 2":4,
			"Triangle Adept 3":5,
			"Pass 1":4,
			"Pass 2":4,
			"Pass 3":4
		},
	},
	"Corrin(F)":{
		"bases":{"hp":19, "atk":8, "spd":6, "def":8, "res":6},
		"growths":{"hp":6, "atk":5, "spd":9, "def":8, "res":3},
		"color":"blue",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":3,
			"Fire Breath+":3,
			"Dark Breath":3,
			"Dark Breath+":5,
			"Dragon Gaze":3,
			"Draconic Aura":4,
			"Seal Res 1":3,
			"Seal Res 2":4,
			"Seal Res 3":5,
			"Hone Atk 1":3,
			"Hone Atk 2":3,
			"Hone Atk 3":4
		},
	},
	"Donnel":{
		"bases":{"hp":17, "atk":7, "spd":5, "def":6, "res":4},
		"growths":{"hp":8, "atk":9, "spd":7, "def":8, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":1,
			"Steel Lance":2,
			"Brave Lance":3,
			"Brave Lance+":5,
			"HP 3":1,
			"HP 4":2,
			"HP 5":4,
			"Drag Back":3
		},
	},
	"Effie":{
		"bases":{"hp":22, "atk":12, "spd":5, "def":11, "res":4},
		"growths":{"hp":9, "atk":9, "spd":4, "def":6, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"armored",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Silver Lance":4,
			"Silver Lance+":5,
			"Death Blow 1":4,
			"Death Blow 2":4,
			"Death Blow 3":5,
			"Wary Fighter 1":4,
			"Wary Fighter 2":4,
			"Wary Fighter 3":4
		},
	},
	"Ephraim":{
		"bases":{"hp":19, "atk":9, "spd":6, "def":8, "res":5},
		"growths":{"hp":8, "atk":8, "spd":5, "def":7, "res":3},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"Heavy Spear":5,
			"Siegmund":5,
			"New Moon":5,
			"Moonbow":5,
			"Seal Def 1":5,
			"Seal Def 2":5,
			"Seal Def 3":5,
			"Threaten Def 1":5,
			"Threaten Def 2":5,
			"Threaten Def 3":5
		},
	},
	"Est":{
		"bases":{"hp":17, "atk":9, "spd":8, "def":5, "res":8},
		"growths":{"hp":5, "atk":8, "spd":6, "def":5, "res":7},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Heavy Spear":3,
			"Heavy Spear+":5,
			"Defiant Res 1":3,
			"Defiant Res 2":3,
			"Defiant Res 3":4,
			"Seal Spd 1":3,
			"Seal Spd 2":4,
			"Seal Spd 3":5
		},
	},
	"Florina":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":6, "res":8},
		"growths":{"hp":7, "atk":6, "spd":5, "def":5, "res":8},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Heavy Spear":3,
			"Heavy Spear+":5,
			"Darting Blow 1":3,
			"Darting Blow 2":3,
			"Darting Blow 3":4,
			"Breath of Life 1":3,
			"Breath of Life 2":4,
			"Breath of Life 3":5
		},
	},
	"Gwendolyn":{
		"bases":{"hp":23, "atk":8, "spd":5, "def":12, "res":6},
		"growths":{"hp":8, "atk":6, "spd":5, "def":8, "res":6},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"armored",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Killer Lance":3,
			"Killer Lance+":5,
			"Buckler":3,
			"Escutcheon":4,
			"Drag Back":3,
			"Hone Atk 1":3,
			"Hone Atk 2":3,
			"Hone Armor":4
		},
	},
	"Hinoka":{
		"bases":{"hp":19, "atk":7, "spd":8, "def":6, "res":7},
		"growths":{"hp":6, "atk":9, "spd":7, "def":5, "res":4},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"Brave Lance":5,
			"Brave Lance+":5,
			"Rising Wind":5,
			"Blazing Wind":5,
			"Defiant Def 1":5,
			"Defiant Def 2":5,
			"Defiant Def 3":5,
			"Hone Spd 1":5,
			"Hone Spd 2":5,
			"Hone Fliers":5
		},
	},
	"Jagen":{
		"bases":{"hp":20, "atk":8, "spd":7, "def":8, "res":11},
		"growths":{"hp":4, "atk":5, "spd":4, "def":4, "res":7},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Silver Lance":3,
			"Silver Lance+":5,
			"Holy Vestments":3,
			"Aegis":4,
			"Fury 1":3,
			"Fury 2":4,
			"Fury 3":5,
			"Fortify Res 1":3,
			"Fortify Res 2":3,
			"Fortify Res 3":4
		},
	},
	"Linde":{
		"bases":{"hp":16, "atk":9, "spd":10, "def":4, "res":5},
		"growths":{"hp":5, "atk":8, "spd":8, "def":1, "res":6},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Thoron":5,
			"Aura":5,
			"Speed 1":5,
			"Speed 2":5,
			"Speed 3":5,
			"Fortify Res 1":5,
			"Fortify Res 2":5,
			"Fortify Res 3":5
		},
	},
	"Ninian":{
		"bases":{"hp":16, "atk":5, "spd":7, "def":6, "res":5},
		"growths":{"hp":8, "atk":5, "spd":8, "def":4, "res":6},
		"color":"blue",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":5,
			"Fire Breath+":5,
			"Light Breath":5,
			"Light Breath+":5,
			"Escape Route 1":5,
			"Escape Route 2":5,
			"Escape Route 3":5,
			"Fortify Def 1":5,
			"Fortify Def 2":5,
			"Fortify Dragons":5
		},
	},
	"Nowi":{
		"bases":{"hp":17, "atk":6, "spd":5, "def":6, "res":5},
		"growths":{"hp":9, "atk":9, "spd":6, "def":7, "res":6},
		"color":"blue",
		"weapontype":"dragon",
		"movetype":"infantry",
		"skills":{
			"Fire Breath":4,
			"Fire Breath+":4,
			"Lightning Breath":4,
			"Lightning Breath+":5,
			"Defense 1":4,
			"Defense 2":4,
			"Defense 3":5,
			"Threaten Res 1":4,
			"Threaten Res 2":4,
			"Threaten Res 3":4
		},
	},
	"Oboro":{
		"bases":{"hp":18, "atk":8, "spd":7, "def":9, "res":5},
		"growths":{"hp":6, "atk":7, "spd":5, "def":8, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Heavy Spear":3,
			"Heavy Spear+":5,
			"Seal Def 1":3,
			"Seal Def 2":3,
			"Seal Def 3":4,
			"Threaten Res 1":3,
			"Threaten Res 2":4,
			"Threaten Res 3":5
		},
	},
	"Odin":{
		"bases":{"hp":19, "atk":5, "spd":8, "def":6, "res":6},
		"growths":{"hp":7, "atk":4, "spd":7, "def":5, "res":5},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":3,
			"Elthunder":3,
			"Blarblade":3,
			"Blarblade+":5,
			"New Moon":3,
			"Moonbow":4,
			"Defiant Atk 1":3,
			"Defiant Atk 2":4,
			"Defiant Atk 3":5,
			"R Tomebreaker 1":3,
			"R Tomebreaker 2":3,
			"R Tomebreaker 3":4
		},
	},
	"Olwen":{
		"bases":{"hp":17, "atk":7, "spd":8, "def":5, "res":6},
		"growths":{"hp":4, "atk":5, "spd":8, "def":3, "res":7},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"cavalry",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Thoron":5,
			"Dire Thunder":5,
			"Warding Blow 1":5,
			"Warding Blow 2":5,
			"Warding Blow 3":5,
			"Spur Res 1":5,
			"Spur Res 2":5,
			"Spur Res 3":5
		},
	},
	"Peri":{
		"bases":{"hp":16, "atk":9, "spd":9, "def":6, "res":6},
		"growths":{"hp":5, "atk":7, "spd":7, "def":4, "res":7},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Killer Lance":4,
			"Killer Lance+":5,
			"Night Sky":4,
			"Glimmer":4,
			"Resistance 1":4,
			"Resistance 2":4,
			"Resistance 3":5,
			"Threaten Def 1":4,
			"Threaten Def 2":4,
			"Threaten Def 3":4
		},
	},
	"Reinhardt":{
		"bases":{"hp":16, "atk":8, "spd":6, "def":5, "res":8},
		"growths":{"hp":6, "atk":7, "spd":4, "def":6, "res":4},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"cavalry",
		"skills":{
			"Thunder":4,
			"Elthunder":4,
			"Thoron":4,
			"Dire Thunder":5,
			"Rising Thunder":4,
			"Blazing Thunder":4,
			"Vantage 1":4,
			"Vantage 2":4,
			"Vantage 3":4,
			"Spur Atk 1":4,
			"Spur Atk 2":4,
			"Goad Cavalry":5
		},
	},
	"Robin(M)":{
		"bases":{"hp":18, "atk":7, "spd":7, "def":7, "res":5},
		"growths":{"hp":6, "atk":6, "spd":6, "def":6, "res":4},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":3,
			"Elthunder":3,
			"Blarraven":3,
			"Blarraven+":5,
			"Glowing Ember":3,
			"Bonfire":4,
			"Defiant Spd 1":3,
			"Defiant Spd 2":4,
			"Defiant Spd 3":5,
			"Spur Def 1":3,
			"Spur Def 2":3,
			"Spur Def 3":4
		},
	},
	"Shanna":{
		"bases":{"hp":17, "atk":8, "spd":9, "def":6, "res":7},
		"growths":{"hp":6, "atk":6, "spd":8, "def":5, "res":6},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Killer Lance":3,
			"Killer Lance+":5,
			"Chilling Wind":3,
			"Iceberg":4,
			"Desperation 1":3,
			"Desperation 2":3,
			"Desperation 3":4,
			"Threaten Spd 1":3,
			"Threaten Spd 2":4,
			"Threaten Spd 3":5
		},
	},
	"Sharena":{
		"bases":{"hp":19, "atk":8, "spd":8, "def":7, "res":5},
		"growths":{"hp":7, "atk":7, "spd":7, "def":6, "res":4},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":2,
			"Steel Lance":2,
			"Silver Lance":3,
			"Fensalir":5,
			"Speed 1":1,
			"Speed 2":2,
			"Speed 3":4,
			"Fortify Def 1":3,
			"Fortify Def 2":4,
			"Fortify Def 3":5
		},
	},
	"Subaki":{
		"bases":{"hp":18, "atk":6, "spd":9, "def":9, "res":5},
		"growths":{"hp":6, "atk":5, "spd":8, "def":8, "res":4},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":1,
			"Steel Lance":2,
			"Sapphire Lance":3,
			"Sapphire Lance+":5,
			"Resistance 1":1,
			"Resistance 2":2,
			"Resistance 3":4,
			"Quick Riposte 1":3,
			"Quick Riposte 2":4,
			"Quick Riposte 3":5
		},
	},
	"Sully":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":7, "res":6},
		"growths":{"hp":7, "atk":5, "spd":8, "def":4, "res":6},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":1,
			"Steel Lance":2,
			"Sapphire Lance":3,
			"Sapphire Lance+":5,
			"Swordbreaker 1":3,
			"Swordbreaker 2":4,
			"Swordbreaker 3":5,
			"Spur Def 1":3,
			"Spur Def 2":3,
			"Spur Def 3":4
		},
	},
	"Ursula":{
		"bases":{"hp":16, "atk":7, "spd":8, "def":4, "res":8},
		"growths":{"hp":5, "atk":6, "spd":7, "def":3, "res":6},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"cavalry",
		"skills":{
			"Thunder":3,
			"Elthunder":3,
			"Blarwolf":3,
			"Blarwolf+":5,
			"Rising Thunder":3,
			"Growing Thunder":4,
			"Death Blow 1":3,
			"Death Blow 2":4,
			"Death Blow 3":5,
			"Threaten Res 1":3,
			"Threaten Res 2":3,
			"Threaten Res 3":4
		},
	},
	"Azama":{
		"bases":{"hp":19, "atk":4, "spd":7, "def":8, "res":6},
		"growths":{"hp":7, "atk":4, "spd":5, "def":7, "res":5},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":3,
			"Pain":3,
			"Imbue":3,
			"Solid-Earth Balm":3,
			"Threaten Atk 1":3,
			"Threaten Atk 2":4,
			"Threaten Atk 3":5
		},
	},
	"Clarine":{
		"bases":{"hp":16, "atk":6, "spd":9, "def":5, "res":7},
		"growths":{"hp":5, "atk":5, "spd":7, "def":4, "res":6},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"cavalry",
		"skills":{
			"Assault":3,
			"Fear":3,
			"Imbue":3,
			"Swift-Winds Balm":3,
			"Resistance 1":3,
			"Resistance 2":4,
			"Resistance 3":5
		},
	},
	"Elise":{
		"bases":{"hp":15, "atk":8, "spd":8, "def":4, "res":8},
		"growths":{"hp":3, "atk":7, "spd":7, "def":3, "res":7},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"cavalry",
		"skills":{
			"Assault":5,
			"Gravity":5,
			"Imbue":5,
			"Kindled-Fire Balm":5,
			"Live to Serve 1":5,
			"Live to Serve 2":5,
			"Live to Serve 3":5
		},
	},
	"Felicia":{
		"bases":{"hp":15, "atk":6, "spd":11, "def":3, "res":9},
		"growths":{"hp":5, "atk":4, "spd":8, "def":3, "res":8},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":1,
			"Steel Dagger":2,
			"Silver Dagger":3,
			"Silver Dagger+":5,
			"Chilling Wind":3,
			"Glacies":4,
			"Resistance 1":3,
			"Resistance 2":4,
			"Resistance 3":5,
			"Breath of Life 1":1,
			"Breath of Life 2":2,
			"Breath of Life 3":4
		},
	},
	"Gaius":{
		"bases":{"hp":18, "atk":7, "spd":10, "def":5, "res":4},
		"growths":{"hp":7, "atk":6, "spd":8, "def":4, "res":3},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":3,
			"Steel Dagger":3,
			"Rogue Dagger":3,
			"Rogue Dagger+":5,
			"Defiant Atk 1":3,
			"Defiant Atk 2":4,
			"Defiant Atk 3":5,
			"Pass 1":3,
			"Pass 2":3,
			"Pass 3":4
		},
	},
	"Gordin":{
		"bases":{"hp":19, "atk":7, "spd":6, "def":8, "res":4},
		"growths":{"hp":7, "atk":7, "spd":5, "def":7, "res":2},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":3,
			"Steel Bow":3,
			"Brave Bow":3,
			"Brave Bow+":5,
			"Attack 1":3,
			"Attack 2":3,
			"Attack 3":4,
			"Vantage 1":3,
			"Vantage 2":4,
			"Vantage 3":5
		},
	},
	"Jaffar":{
		"bases":{"hp":17, "atk":7, "spd":9, "def":6, "res":5},
		"growths":{"hp":7, "atk":5, "spd":7, "def":5, "res":4},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":5,
			"Steel Dagger":5,
			"Silver Dagger":5,
			"Deathly Dagger":5,
			"Night Sky":5,
			"Glimmer":5,
			"Life and Death 1":5,
			"Life and Death 2":5,
			"Life and Death 3":5,
			"Threaten Spd 1":5,
			"Threaten Spd 2":5,
			"Threaten Spd 3":5
		},
	},
	"Jakob":{
		"bases":{"hp":17, "atk":7, "spd":9, "def":6, "res":5},
		"growths":{"hp":6, "atk":6, "spd":6, "def":5, "res":5},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":4,
			"Steel Dagger":4,
			"Silver Dagger":4,
			"Silver Dagger+":5,
			"Defense 1":4,
			"Defense 2":4,
			"Defense 3":4,
			"Renewal 1":4,
			"Renewal 2":4,
			"Renewal 3":5
		},
	},
	"Jeorge":{
		"bases":{"hp":18, "atk":8, "spd":8, "def":5, "res":5},
		"growths":{"hp":5, "atk":7, "spd":7, "def":5, "res":4},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":4,
			"Steel Bow":4,
			"Silver Bow":4,
			"Parthia":5,
			"Rising Flame":4,
			"Blazing Flame":5,
			"Seal Atk 1":4,
			"Seal Atk 2":4,
			"Seal Atk 3":4,
			"Spur Spd 1":4,
			"Spur Spd 2":4,
			"Spur Spd 3":5
		},
	},
	"Kagero":{
		"bases":{"hp":16, "atk":9, "spd":8, "def":5, "res":6},
		"growths":{"hp":3, "atk":8, "spd":7, "def":4, "res":6},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":4,
			"Steel Dagger":4,
			"Poison Dagger":4,
			"Poison Dagger+":5,
			"Retribution":4,
			"Reprisal":4,
			"Warding Blow 1":4,
			"Warding Blow 2":4,
			"Warding Blow 3":5,
			"Daggerbreaker 1":4,
			"Daggerbreaker 2":4,
			"Daggerbreaker 3":4
		},
	},
	"Klein":{
		"bases":{"hp":18, "atk":9, "spd":7, "def":5, "res":5},
		"growths":{"hp":6, "atk":6, "spd":8, "def":3, "res":5},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":4,
			"Steel Bow":4,
			"Brave Bow":4,
			"Brave Bow+":5,
			"Chilling Wind":4,
			"Glacies":4,
			"Death Blow 1":4,
			"Death Blow 2":4,
			"Death Blow 3":4,
			"Quick Riposte 1":4,
			"Quick Riposte 2":4,
			"Quick Riposte 3":5
		},
	},
	"Lachesis":{
		"bases":{"hp":17, "atk":7, "spd":5, "def":5, "res":8},
		"growths":{"hp":6, "atk":8, "spd":4, "def":4, "res":6},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":4,
			"Absorb":4,
			"Imbue":4,
			"Solid-Earth Balm":4,
			"Spur Res 1":4,
			"Spur Res 2":4,
			"Spur Res 3":5
		},
	},
	"Lissa":{
		"bases":{"hp":17, "atk":7, "spd":6, "def":6, "res":8},
		"growths":{"hp":6, "atk":5, "spd":5, "def":6, "res":6},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":1,
			"Gravity":3,
			"Imbue":2,
			"Kindled-Fire Balm":3,
			"Renewal 1":3,
			"Renewal 2":4,
			"Renewal 3":5
		},
	},
	"Lucius":{
		"bases":{"hp":18, "atk":6, "spd":8, "def":3, "res":9},
		"growths":{"hp":5, "atk":8, "spd":6, "def":1, "res":8},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":4,
			"Pain":4,
			"Imbue":4,
			"Miracle":4,
			"HP 3":4,
			"HP 4":4,
			"HP 5":5
		},
	},
	"Maria":{
		"bases":{"hp":17, "atk":5, "spd":8, "def":4, "res":10},
		"growths":{"hp":5, "atk":6, "spd":8, "def":3, "res":6},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":4,
			"Panic":4,
			"Imbue":4,
			"Miracle":4,
			"Fortify Res 1":4,
			"Fortify Res 2":4,
			"Fortify Res 3":5
		},
	},
	"Matthew":{
		"bases":{"hp":17, "atk":6, "spd":10, "def":6, "res":5},
		"growths":{"hp":7, "atk":5, "spd":7, "def":7, "res":2},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":2,
			"Steel Dagger":2,
			"Rogue Dagger":3,
			"Rogue Dagger+":5,
			"Poison Strike 1":3,
			"Poison Strike 2":4,
			"Poison Strike 3":5,
			"Hone Spd 1":2,
			"Hone Spd 2":2,
			"Hone Spd 3":4
		},
	},
	"Niles":{
		"bases":{"hp":18, "atk":6, "spd":8, "def":4, "res":8},
		"growths":{"hp":5, "atk":5, "spd":8, "def":2, "res":8},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":3,
			"Steel Bow":3,
			"Killer Bow":3,
			"Killer Bow+":5,
			"Chilling Wind":3,
			"Iceberg":4,
			"Warding Blow 1":3,
			"Warding Blow 2":3,
			"Warding Blow 3":4,
			"Spur Res 1":3,
			"Spur Res 2":4,
			"Spur Res 3":5
		},
	},
	"Priscilla":{
		"bases":{"hp":17, "atk":7, "spd":7, "def":4, "res":8},
		"growths":{"hp":5, "atk":6, "spd":6, "def":3, "res":7},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"cavalry",
		"skills":{
			"Assault":4,
			"Panic":4,
			"Imbue":4,
			"Still-Water Balm":4,
			"Spur Def 1":4,
			"Spur Def 2":4,
			"Spur Def 3":5
		},
	},
	"Rebecca":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":6, "res":5},
		"growths":{"hp":5, "atk":6, "spd":8, "def":3, "res":6},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":4,
			"Steel Bow":4,
			"Silver Bow":4,
			"Silver Bow+":5,
			"Darting Blow 1":4,
			"Darting Blow 2":4,
			"Darting Blow 3":4,
			"Seal Atk 1":4,
			"Seal Atk 2":4,
			"Seal Atk 3":5
		},
	},
	"Saizo":{
		"bases":{"hp":17, "atk":7, "spd":8, "def":9, "res":3},
		"growths":{"hp":5, "atk":6, "spd":8, "def":7, "res":2},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":3,
			"Steel Dagger":3,
			"Smoke Dagger":3,
			"Smoke Dagger+":5,
			"Poison Strike 1":3,
			"Poison Strike 2":3,
			"Poison Strike 3":4,
			"Spur Spd 1":3,
			"Spur Spd 2":4,
			"Spur Spd 3":5
		},
	},
	"Sakura":{
		"bases":{"hp":17, "atk":6, "spd":8, "def":5, "res":8},
		"growths":{"hp":5, "atk":6, "spd":6, "def":5, "res":6},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":4,
			"Fear":4,
			"Imbue":4,
			"Still-Water Balm":4,
			"Fortify Def 1":4,
			"Fortify Def 2":4,
			"Fortify Def 3":5
		},
	},
	"Serra":{
		"bases":{"hp":16, "atk":6, "spd":9, "def":4, "res":9},
		"growths":{"hp":4, "atk":7, "spd":6, "def":4, "res":7},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":3,
			"Absorb":3,
			"Imbue":3,
			"Swift-Winds Balm":3,
			"Hone Atk 1":3,
			"Hone Atk 2":4,
			"Hone Atk 3":5
		},
	},
	"Setsuna":{
		"bases":{"hp":18, "atk":6, "spd":9, "def":5, "res":6},
		"growths":{"hp":5, "atk":6, "spd":9, "def":4, "res":4},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":3,
			"Steel Bow":3,
			"Assassin's Bow":3,
			"Assassin's Bow+":5,
			"HP 3":3,
			"HP 4":4,
			"HP 5":5,
			"Bowbreaker 1":3,
			"Bowbreaker 2":3,
			"Bowbreaker 3":4
		},
	},
	"Takumi":{
		"bases":{"hp":18, "atk":8, "spd":7, "def":6, "res":5},
		"growths":{"hp":6, "atk":7, "spd":8, "def":5, "res":2},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":5,
			"Steel Bow":5,
			"Silver Bow":5,
			"Fujin Yumi":5,
			"Retribution":5,
			"Vengeance":5,
			"Close Counter":5,
			"Threaten Spd 1":5,
			"Threaten Spd 2":5,
			"Threaten Spd 3":5
		},
	},
	"Virion":{
		"bases":{"hp":20, "atk":7, "spd":7, "def":7, "res":3},
		"growths":{"hp":8, "atk":7, "spd":7, "def":5, "res":1},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":1,
			"Steel Bow":2,
			"Silver Bow":3,
			"Silver Bow+":5,
			"Night Sky":3,
			"Astra":4,
			"Defiant Res 1":3,
			"Defiant Res 2":4,
			"Defiant Res 3":5,
			"Seal Spd 1":1,
			"Seal Spd 2":2,
			"Seal Spd 3":4
		},
	},
	"Wrys":{
		"bases":{"hp":18, "atk":5, "spd":6, "def":5, "res":10},
		"growths":{"hp":7, "atk":5, "spd":4, "def":4, "res":8},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":1,
			"Slow":3,
			"Imbue":2,
			"Heavenly Light":3,
			"Live to Serve 1":3,
			"Live to Serve 2":4,
			"Live to Serve 3":5
		},
	},
	"Michalis":{
		"bases":{"hp":19, "atk":8, "spd":7, "def":9, "res":4},
		"growths":{"hp":7, "atk":8, "spd":5, "def":8, "res":3},
		"color":"green",
		"weapontype":"axe",
		"movetype":"flying",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Silver Axe":3,
			"Hauteclere":5,
			"Rising Thunder":3,
			"Blazing Thunder":4,
			"Iote's Shield":3,
			"Threaten Def 1":3,
			"Threaten Def 2":3,
			"Threaten Def 3":4,
		},
	},
	"Lucina (Spring)":{
		"bases":{"hp":16, "atk":7, "spd":10, "def":5, "res":6},
		"growths":{"hp":5, "atk":6, "spd":8, "def":4, "res":5},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Blue Egg":5,
			"Blue Egg+":5,
			"Darting Blow 1":5,
			"Swift Sparrow 1":5,
			"Swift Sparrow 2":5,
			"Seal Res 1":5,
			"Seal Res 2":5,
			"Seal Res 3":5
		},
	},
	"Camilla (Spring)":{
		"bases":{"hp":17, "atk":9, "spd":6, "def":8, "res":4},
		"growths":{"hp":6, "atk":8, "spd":5, "def":6, "res":3},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"flying",
		"skills":{
			"Wind":5,
			"Elwind":5,
			"Green Egg":5,
			"Green Egg+":5,
			"Defiant Spd 1":5,
			"Defiant Spd 2":5,
			"Defiant Spd 3":5,
			"Live for Bounty":5
		},
	},
	"Xander (Spring)":{
		"bases":{"hp":18, "atk":6, "spd":6, "def":9, "res":7},
		"growths":{"hp":6, "atk":5, "spd":6, "def":8, "res":5},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"Carrot Lance":5,
			"Carrot Lance+":5,
			"Live for Honor":5,
			"Fortify Def 1":5,
			"Fortify Def 2":5,
			"Fortify Def 3":5
		},
	},
	"Chrom (Spring)":{
		"bases":{"hp":19, "atk":9, "spd":8, "def":6, "res":5},
		"growths":{"hp":7, "atk":8, "spd":7, "def":6, "res":3},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":5,
			"Steel Axe":5,
			"Carrot Axe":5,
			"Carrot Axe+":5,
			"Defense 1":5,
			"Attack Def 1":5,
			"Attack Def 2":5,
			"Axe Experience 1":5,
			"Axe Experience 2":5,
			"Axe Experience 3":5
		},
	},
	"Navarre":{
		"bases":{"hp":18, "atk":7, "spd":11, "def":6, "res":5},
		"growths":{"hp":7, "atk":7, "spd":8, "def":4, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Killing Edge":3,
			"Killing Edge+":5,
			"Rising Wind":3,
			"Blazing Wind":4,
			"Desperation 1":3,
			"Desperation 2":4,
			"Desperation 3":5,
			"Threaten Spd 1":3,
			"Threaten Spd 2":3,
			"Threaten Spd 3":4
		},
	},
	"Alm":{
		"bases":{"hp":21, "atk":9, "spd":6, "def":6, "res":5},
		"growths":{"hp":7, "atk":7, "spd":7, "def":6, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Silver Sword":5,
			"Falchion":5,
			"Dragon Gaze":5,
			"Draconic Aura":5,
			"Attack 1":5,
			"Attack 2":5,
			"Attack 3":5,
			"Windsweep 1":5,
			"Windsweep 2":5,
			"Windsweep 3":5
		},
	},
	"Clair":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":5, "res":9},
		"growths":{"hp":5, "atk":5, "spd":9, "def":5, "res":7},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"flying",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Silver Lance":4,
			"Silver Lance+":5,
			"Hit and Run":4,
			"Spur Spd 1":4,
			"Spur Spd 2":4,
			"Spur Spd 3":5
		},
	},
	"Lukas":{
		"bases":{"hp":19, "atk":9, "spd":5, "def":10, "res":4},
		"growths":{"hp":8, "atk":8, "spd":4, "def":9, "res":2},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Killer Lance":4,
			"Killer Lance+":5,
			"Holy Vestments":4,
			"Sacred Cowl":4,
			"Fortress Def 1":4,
			"Fortress Def 2":4,
			"Fortress Def 3":5,
			"Obstruct 1":4,
			"Obstruct 2":4,
			"Obstruct 3":4
		},
	},
	"Faye":{
		"bases":{"hp":16, "atk":6, "spd":3, "def":4, "res":7},
		"growths":{"hp":8, "atk":7, "spd":6, "def":6, "res":7},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":5,
			"Steel Bow":5,
			"Firesweep Bow":5,
			"Firesweep Bow+":5,
			"Daylight":5,
			"Noontime":5,
			"Wings of Mercy 1":5,
			"Wings of Mercy 2":5,
			"Wings of Mercy 3":5,
			"Bow Experience 1":5,
			"Bow Experience 2":5,
			"Bow Experience 3":5
		},
	},
	"Zephiel":{
		"bases":{"hp":25, "atk":9, "spd":3, "def":12, "res":5},
		"growths":{"hp":10, "atk":8, "spd":2, "def":8, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"armored",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Silver Sword":3,
			"Eckesachs":5,
			"Retribution":3,
			"Reprisal":4,
			"Life and Death 1":4,
			"Life and Death 2":4,
			"Life and Death 3":5,
			"Wary Fighter 1":4,
			"Wary Fighter 2":4,
			"Wary Fighter 3":4
		},
	},
	"Ike":{
		"bases":{"hp":18, "atk":9, "spd":7, "def":8, "res":5},
		"growths":{"hp":7, "atk":8, "spd":7, "def":7, "res":2},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Silver Sword":5,
			"Ragnell":5,
			"New Moon":5,
			"Luna":5,
			"Aether":5,
			"Heavy Blade 1":5,
			"Heavy Blade 2":5,
			"Heavy Blade 3":5,
			"Swordbreaker 1":5,
			"Swordbreaker 2":5,
			"Swordbreaker 3":5
		},
	},
	"Mist":{
		"bases":{"hp":17, "atk":8, "spd":6, "def":5, "res":8},
		"growths":{"hp":6, "atk":5, "spd":6, "def":3, "res":8},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":5,
			"Slow":5,
			"Imbue":5,
			"Miracle":5,
			"Spur Res 1":5,
			"Spur Def Res 1":5,
			"Spur Def Res 2":5
		},
	},
	"Soren":{
		"bases":{"hp":17, "atk":7, "spd":9, "def":4, "res":7},
		"growths":{"hp":5, "atk":8, "spd":7, "def":2, "res":6},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":4,
			"Elwind":4,
			"Rexcalibur":4,
			"Rexcalibur+":5,
			"Rising Wind":4,
			"Growing Wind":4,
			"Watersweep 1":4,
			"Watersweep 2":4,
			"Watersweep 3":5,
			"Fortify Res 1":4,
			"Fortify Res 2":4,
			"Fortify Res 3":4
		},
	},
	"Titania":{
		"bases":{"hp":18, "atk":6, "spd":8, "def":6, "res":8},
		"growths":{"hp":5, "atk":6, "spd":8, "def":5, "res":6},
		"color":"green",
		"weapontype":"axe",
		"movetype":"cavalry",
		"skills":{
			"Iron Axe":4,
			"Steel Axe":4,
			"Emerald Axe":4,
			"Emerald Axe+":5,
			"Armored Blow 1":4,
			"Armored Blow 2":4,
			"Armored Blow 3":4,
			"Guard 1":4,
			"Guard 2":4,
			"Guard 3":5
		},
	},
	"Xander":{
		"bases":{"hp":20, "atk":8, "spd":5, "def":9, "res":4},
		"growths":{"hp":7, "atk":7, "spd":5, "def":9, "res":2},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Silver Sword":3,
			"Siegfried":5,
			"Rising Light":3,
			"Blazing Light":4,
			"Armored Blow 1":5,
			"Armored Blow 2":5,
			"Armored Blow 3":5,
			"Spur Def 1":4,
			"Spur Def 2":4,
			"Spur Def 3":5
		},
	},
	"Boey":{
		"bases":{"hp":19, "atk":7, "spd":5, "def":8, "res":5},
		"growths":{"hp":7, "atk":6, "spd":6, "def":7, "res":2},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":4,
			"Elwind":4,
			"Gronnowl":4,
			"Gronnowl+":5,
			"Glowing Ember":4,
			"Ignis":4,
			"Earth Boost 1":4,
			"Earth Boost 2":4,
			"Earth Boost 3":4,
			"Renewal 1":4,
			"Renewal 2":4,
			"Renewal 3":5
		},
	},
	"Celica":{
		"bases":{"hp":17, "atk":8, "spd":7, "def":5, "res":7},
		"growths":{"hp":6, "atk":7, "spd":8, "def":4, "res":3},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Fire":5,
			"Elfire":5,
			"Bolganone":5,
			"Ragnarok":5,
			"Rising Light":5,
			"Blazing Light":5,
			"Distant Def 1":5,
			"Distant Def 2":5,
			"Distant Def 3":5,
			"Spur Def 1":5,
			"Spur Def 2":5,
			"Spur Def 3":5
		},
	},
	"Genny":{
		"bases":{"hp":17, "atk":9, "spd":6, "def":4, "res":8},
		"growths":{"hp":3, "atk":8, "spd":5, "def":4, "res":8},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":5,
			"Gravity":5,
			"Imbue":5,
			"Heavenly Light":5,
			"Wrathful Staff 1":5,
			"Wrathful Staff 2":5,
			"Wrathful Staff 3":5
		},
	},
	"Mae":{
		"bases":{"hp":16, "atk":10, "spd":7, "def":3, "res":8},
		"growths":{"hp":5, "atk":8, "spd":7, "def":2, "res":6},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":4,
			"Elthunder":4,
			"Blarowl":4,
			"Blarowl+":5,
			"Desperation 1":4,
			"Desperation 2":4,
			"Desperation 3":5,
			"B Tome Exp. 1":4,
			"B Tome Exp. 2":4,
			"B Tome Exp. 3":4
		},
	},
	"Lloyd":{
		"bases":{"hp":17, "atk":8, "spd":9, "def":5, "res":8},
		"growths":{"hp":7, "atk":7, "spd":8, "def":3, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":3,
			"Steel Sword":3,
			"Silver Sword":3,
			"Regal Blade":5,
			"Chilling Wind":3,
			"Iceberg":4,
			"Pass 1":4,
			"Pass 2":4,
			"Pass 3":4,
			"Threaten Atk 1":4,
			"Threaten Atk 2":4,
			"Threaten Atk 3":5
		},
	},
	"Caeda (Bride)":{
		"bases":{"hp":16, "atk":7, "spd":9, "def":4, "res":8},
		"growths":{"hp":4, "atk":6, "spd":9, "def":3, "res":6},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Blessed Bouquet":5,
			"Blessed Bouquet+":5,
			"Chilling Wind":5,
			"Iceberg":5,
			"Hone Spd 1":5,
			"Hone Spd 2":5,
			"Hone Spd 3":5
		},
	},
	"Camus":{
		"bases":{"hp":18, "atk":8, "spd":9, "def":7, "res":4},
		"growths":{"hp":7, "atk":7, "spd":7, "def":7, "res":2},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Silver Lance":3,
			"Gradivus":5,
			"Rising Thunder":3,
			"Growing Thunder":4,
			"Grani's Shield":4,
			"Spur Atk 1":4,
			"Spur Atk 2":4,
			"Goad Cavalry":4
		},
	},
	"Charlotte (Bride)":{
		"bases":{"hp":20, "atk":10, "spd":8, "def":5, "res":4},
		"growths":{"hp":8, "atk":8, "spd":7, "def":5, "res":3},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"First Bite":5,
			"First Bite+":5,
			"Wind Boost 1":5,
			"Wind Boost 2":5,
			"Wind Boost 3":5,
			"Threaten Atk 1":5,
			"Threaten Atk 2":5,
			"Threaten Atk 3":5
		},
	},
	"Cordelia (Bride)":{
		"bases":{"hp":17, "atk":9, "spd":9, "def":4, "res":5},
		"growths":{"hp":5, "atk":8, "spd":8, "def":3, "res":4},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":5,
			"Steel Bow":5,
			"Cupid Arrow":5,
			"Cupid Arrow+":5,
			"Escape Route 1":5,
			"Escape Route 2":5,
			"Escape Route 3":5,
			"Breath of Life 1":5,
			"Breath of Life 2":5,
			"Breath of Life 3":5
		},
	},
	"Lyn (Bride)":{
		"bases":{"hp":17, "atk":6, "spd":10, "def":6, "res":5},
		"growths":{"hp":6, "atk":6, "spd":7, "def":4, "res":5},
		"color":"gray",
		"weapontype":"staff",
		"movetype":"infantry",
		"skills":{
			"Assault":5,
			"Candlelight":5,
			"Imbue":5,
			"Swift-Winds Balm":5,
			"Dazzling Staff 1":5,
			"Dazzling Staff 2":5,
			"Dazzling Staff 3":5
		},
	},
	"Marth (Masked)":{
		"bases":{"hp":19, "atk":8, "spd":10, "def":6, "res":4},
		"growths":{"hp":7, "atk":8, "spd":8, "def":5, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Silver Sword":4,
			"Falchion":5
		},
	},
	"Katarina":{
		"bases":{"hp":17, "atk":6, "spd":8, "def":5, "res":8},
		"growths":{"hp":4, "atk":8, "spd":8, "def":1, "res":7},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Fire":5,
			"Elfire":5,
			"Raudrowl":5,
			"Raudrowl+":5,
			"Chilling Wind":5,
			"Glacies":5,
			"Death Blow 1":5,
			"Swift Sparrow 1":5,
			"Swift Sparrow 2":5,
			"Atk Ploy 1":5,
			"Atk Ploy 2":5,
			"Atk Ploy 3":5
		},
	},
	"Athena":{
		"bases":{"hp":17, "atk":7, "spd":10, "def":8, "res":5},
		"growths":{"hp":5, "atk":7, "spd":9, "def":5, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Wo Dao":4,
			"Wo Dao+":5,
			"New Moon":4,
			"Moonbow":4,
			"Armored Blow 1":4,
			"Sturdy Blow 1":4,
			"Sturdy Blow 2":5,
			"Sword Exp. 1":4,
			"Sword Exp. 2":4,
			"Sword Exp. 3":4
		},
	},
	"Roderick":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":6, "res":7},
		"growths":{"hp":6, "atk":7, "spd":8, "def":5, "res":4},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Firesweep Lance":4,
			"Firesweep Lance+":5,
			"Drag Back":4,
			"Spur Def 1":4,
			"Drive Def 1":4,
			"Drive Def 2":5
		},
	},
	"Luke":{
		"bases":{"hp":19, "atk":8, "spd":6, "def":8, "res":5},
		"growths":{"hp":7, "atk":8, "spd":6, "def":6, "res":3},
		"color":"red",
		"weapontype":"sword",
		"movetype":"cavalry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Brave Sword":5,
			"Brave Sword+":5,
			"Glowing Ember":5,
			"Bonfire":5,
			"Fire Boost 1":5,
			"Fire Boost 2":5,
			"Fire Boost 3":5,
			"Panic Ploy 1":5,
			"Panic Ploy 2":5,
			"Panic Ploy 3":5
		},
	},
	"Legion":{
		"bases":{"hp":20, "atk":10, "spd":9, "def":5, "res":3},
		"growths":{"hp":8, "atk":8, "spd":8, "def":4, "res":3},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":3,
			"Steel Axe":3,
			"Legion's Axe":3,
			"Legion's Axe+":5,
			"Retribution":3,
			"Reprisal":4,
			"Fury 1":4,
			"Fury 2":4,
			"Fury 3":5,
			"Obstruct 1":3,
			"Obstruct 2":3,
			"Obstruct 3":4
		},
	},
	"Clarisse":{
		"bases":{"hp":18, "atk":7, "spd":8, "def":6, "res":5},
		"growths":{"hp":5, "atk":7, "spd":8, "def":5, "res":3},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":3,
			"Steel Bow":3,
			"Clarisse's Bow":3,
			"Clarisse's Bow+":5,
			"Night Sky":3,
			"Glimmer":4,
			"Poison Strike 1":3,
			"Poison Strike 2":3,
			"Poison Strike 3":4,
			"Threaten Def 1":3,
			"Threaten Def 2":4,
			"Threaten Def 3":5
		},
	},
	"Frederick (Summer)":{
		"bases":{"hp":18, "atk":8, "spd":7, "def":6, "res":5},
		"growths":{"hp":6, "atk":7, "spd":7, "def":6, "res":2},
		"color":"gray",
		"weapontype":"dagger",
		"movetype":"infantry",
		"skills":{
			"Iron Dagger":5,
			"Steel Dagger":5,
			"Seashell":5,
			"Seashell+":5,
			"Armored Blow 1":5,
			"Armored Blow 2":5,
			"Armored Blow 3":5,
			"Seal Spd 1":5,
			"Seal Atk Spd 1":5,
			"Seal Atk Spd 2":5
		},
	},
	"Gaius (Summer)":{
		"bases":{"hp":17, "atk":8, "spd":9, "def":4, "res":6},
		"growths":{"hp":4, "atk":6, "spd":9, "def":3, "res":6},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":5,
			"Steel Bow":5,
			"Refreshing Bolt":5,
			"Refreshing Bolt+":5,
			"Night Sky":5,
			"Astra":5,
			"Vantage 1":5,
			"Vantage 2":5,
			"Vantage 3":5,
			"Def Ploy 1":5,
			"Def Ploy 2":5,
			"Def Ploy 3":5
		},
	},
	"Robin(F) (Summer)":{
		"bases":{"hp":18, "atk":8, "spd":8, "def":6, "res":7},
		"growths":{"hp":4, "atk":7, "spd":8, "def":6, "res":6},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"infantry",
		"skills":{
			"Iron Lance":5,
			"Steel Lance":5,
			"Deft Harpoon":5,
			"Deft Harpoon+":5,
			"Defense 1":5,
			"HP Def 1":5,
			"HP Def 2":5,
			"Lance Valor 1":5,
			"Lance Valor 2":5,
			"Lance Valor 3":5
		},
	},
	"Tiki(A) (Summer)":{
		"bases":{"hp":18, "atk":8, "spd":6, "def":8, "res":7},
		"growths":{"hp":4, "atk":9, "spd":7, "def":7, "res":4},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":5,
			"Steel Axe":5,
			"Melon Crusher":5,
			"Melon Crusher+":5,
			"Daylight":5,
			"Sol":5,
			"Close Def 1":5,
			"Close Def 2":5,
			"Close Def 3":5,
			"Axe Valor 1":5,
			"Axe Valor 2":5,
			"Axe Valor 3":5
		},
	},
	"Tobin":{
		"bases":{"hp":18, "atk":7, "spd":5, "def":5, "res":4},
		"growths":{"hp":9, "atk":7, "spd":6, "def":9, "res":6},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":4,
			"Steel Sword":4,
			"Armorslayer":4,
			"Armorslayer+":5,
			"Attack 1":4,
			"Attack 2":4,
			"Attack 3":4,
			"Seal Spd 1":4,
			"Seal Spd 2":4,
			"Seal Spd 3":5
		},
	},
	"Sonya":{
		"bases":{"hp":17, "atk":7, "spd":7, "def":5, "res":8},
		"growths":{"hp":5, "atk":8, "spd":7, "def":1, "res":7},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":5,
			"Elwind":5,
			"Rexcalibur":5,
			"Dark Excalibur":5,
			"New Moon":5,
			"Moonbow":5,
			"Warding Blow 1":5,
			"Mirror Strike 1":5,
			"Mirror Strike 2":5,
			"Res Ploy 1":5,
			"Res Ploy 2":5,
			"Res Ploy 3":5
		},
	},
	"Saber":{
		"bases":{"hp":18, "atk":7, "spd":9, "def":8, "res":5},
		"growths":{"hp":6, "atk":7, "spd":7, "def":7, "res":4},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Slaying Edge":5,
			"Slaying Edge+":5,
			"Holy Vestments":5,
			"Aegis":5,
			"HP 3":5,
			"HP Spd 1":5,
			"HP Spd 2":5,
			"Shield Pulse 1":5,
			"Shield Pulse 2":5,
			"Shield Pulse 3":5,
		},
	},
	"Mathilda":{
		"bases":{"hp":16, "atk":7, "spd":8, "def":7, "res":8},
		"growths":{"hp":5, "atk":6, "spd":7, "def":4, "res":8},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":4,
			"Steel Lance":4,
			"Ridersbane":4,
			"Ridersbane+":5,
			"Cancel Affinity 1":4,
			"Cancel Affinity 2":4,
			"Cancel Affinity 3":5,
			"Hone Atk 1":4,
			"Hone Atk 2":4,
			"Hone Atk 3":4,
		},
	},
	"Leon":{
		"bases":{"hp":17, "atk":8, "spd":6, "def":8, "res":5},
		"growths":{"hp":6, "atk":8, "spd":7, "def":6, "res":1},
		"color":"gray",
		"weapontype":"bow",
		"movetype":"infantry",
		"skills":{
			"Iron Bow":4,
			"Steel Bow":4,
			"Slaying Bow":4,
			"Slaying Bow+":5,
			"Glowing Ember":4,
			"Ignis":4,
			"Speed 1":4,
			"Speed 2":4,
			"Speed 3":4,
			"Guard 1":4,
			"Guard 2":4,
			"Guard 3":5,
		},
	},
	"Gray":{
		"bases":{"hp":17, "atk":7, "spd":6, "def":6, "res":3},
		"growths":{"hp":8, "atk":9, "spd":8, "def":7, "res":5},
		"color":"red",
		"weapontype":"sword",
		"movetype":"infantry",
		"skills":{
			"Iron Sword":5,
			"Steel Sword":5,
			"Zanbato":5,
			"Zanbato+":5,
			"Wind Boost 1":5,
			"Wind Boost 2":5,
			"Wind Boost 3":5,
			"Sword Valor 1":5,
			"Sword Valor 2":5,
			"Sword Valor 3":5,
		},
	},
	"Delthea":{
		"bases":{"hp":16, "atk":10, "spd":8, "def":3, "res":7},
		"growths":{"hp":4, "atk":8, "spd":8, "def":1, "res":7},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"infantry",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Thoron":5,
			"Dark Aura":5,
			"Miracle":5,
			"Death Blow 1":5,
			"Death Blow 2":5,
			"Death Blow 3":5,
			"Spur Atk 1":5,
			"Drive Atk 1":5,
			"Drive Atk 2":5,
		},
	},
	"Berkut":{
		"bases":{"hp":19, "atk":8, "spd":5, "def":7, "res":7},
		"growths":{"hp":7, "atk":8, "spd":4, "def":7, "res":4},
		"color":"blue",
		"weapontype":"lance",
		"movetype":"cavalry",
		"skills":{
			"Iron Lance":3,
			"Steel Lance":3,
			"Berkut's Lance":3,
			"Berkut's Lance+":5,
			"Rising Flame":3,
			"Blazing Flame":4,
			"Water Boost 1":4,
			"Water Boost 2":4,
			"Water Boost 3":5,
			"Spur Res 1":4,
			"Spur Res 2":4,
			"Ward Cavalry":4,
		},
	},
	"Xander (Summer)":{
		"bases":{"hp":19, "atk":8, "spd":6, "def":8, "res":6},
		"growths":{"hp":7, "atk":7, "spd":7, "def":9, "res":1},
		"color":"green",
		"weapontype":"axe",
		"movetype":"infantry",
		"skills":{
			"Iron Axe":5,
			"Steel Axe":5,
			"Lilith Floatie":5,
			"Lilith Floatie+":5,
			"Glowing Ember":5,
			"Bonfire":5,
			"Fire Boost 1":5,
			"Fire Boost 2":5,
			"Fire Boost 3":5,
			"Infantry Pulse 1":5,
			"Infantry Pulse 2":5,
			"Infantry Pulse 3":5,
		},
	},
	"Leo (Summer)":{
		"bases":{"hp":18, "atk":8, "spd":5, "def":6, "res":7},
		"growths":{"hp":5, "atk":7, "spd":6, "def":1, "res":9},
		"color":"red",
		"weapontype":"redtome",
		"movetype":"infantry",
		"skills":{
			"Flux":5,
			"Ruin":5,
			"Tomato Tome":5,
			"Tomato Tome+":5,
			"Chilling Wind":5,
			"Iceberg":5,
			"Seal Res 1":5,
			"Seal Res 2":5,
			"Seal Res 3":5,
			"Atk Ploy 1":5,
			"Atk Ploy 2":5,
			"Atk Ploy 3":5,
		},
	},
	"Elise (Summer)":{
		"bases":{"hp":17, "atk":10, "spd":8, "def":3, "res":6},
		"growths":{"hp":4, "atk":8, "spd":8, "def":3, "res":5},
		"color":"green",
		"weapontype":"greentome",
		"movetype":"infantry",
		"skills":{
			"Wind":5,
			"Elwind":5,
			"Hibiscus Tome":5,
			"Hibiscus Tome+":5,
			"Speed 1":5,
			"Spd Res 1":5,
			"Spd Res 2":5,
			"G Tome Valor 1":5,
			"G Tome Valor 2":5,
			"G Tome Valor 3":5,
		},
	},
	"Corrin(F) (Summer)":{
		"bases":{"hp":17, "atk":7, "spd":8, "def":5, "res":7},
		"growths":{"hp":4, "atk":7, "spd":8, "def":4, "res":5},
		"color":"blue",
		"weapontype":"bluetome",
		"movetype":"flying",
		"skills":{
			"Thunder":5,
			"Elthunder":5,
			"Sealife Tome":5,
			"Sealife Tome+":5,
			"Dragon Gaze":5,
			"Dragon Fang":5,
			"Darting Blow 1":5,
			"Swift Strike 1":5,
			"Swift Strike 2":5,
			"Fortify Res 1":5,
			"Fortify Res 2":5,
			"Fortify Fliers":5,
		},
	},
}