# Initial data by /r/AnduCrandu
# Python conversion and revisions by /r/Meteorchestra

#####
# SKILL ATTRIBUTES
# slot: Which skill slot a skill is for
# sp: How much sp a skill costs to learn
# atk/spd/def/res: Basic stat modifiers (weapons, Life and Death, Fury, etc.)
# inheritrule: What types of units can inherit a skill
# 	- Can be a weapon type, movement type, or color
#	- Can be prefixed with 'non' to indicate that only the specified type cannot inherit
#	- Can be comma-separated to indicate several rules must be met
#	- The rule "unique" means it cannot be inherited, the rule "" means anyone can inherit
# rulestomatch: Indicates a number of the inherit rules that must be met, if not all
# affectsduel: Indicates whether a skill affects a duel
# ismax: Indicates that there is no other skill strictly superior to the skill
# turnstotrigger: A count of turns for this unit after which an effect triggers
# triggereffect: The effect that occurs when enough turns have passed
#	Types of trigger effects:
#		renew: Heal the unit by the specified value
# precharge: One-time bonus to special charge at the start of a battle
# charge: Modifiers to special cooldown (this is what charge resets to instead of 0, so Killer weapons have 1, etc.)
# advantage: Indicates a weapon type that this weapon has triangle advantage against outside the usual triangle
# ploy: A turn-start debuff that does not apply if the enemy is ranged and the 'diagonal' ploy behavior option is set
# threaten: A turn-start debuff
# buff: A turn-start buff
# spur: A temporary stacking combat stat bonus
# seal: A post-combat debuff
#	- Includes 'panic' and 'blind' (Candlelight effect)
# postbuff: A post-combat buff
# postheal: A post-combat heal
# blade: Gain attack bonus based on sum of buffs
# specialboost: Damage bonus when offensive specials are triggered
# specialshield: Damage reduction when defensive specials are triggered
# special: Flag for offensive or defensive specials (some unique specials have their own attribute)
#	- type: 'offense' or 'defense' or 'AOE'
#	- range: range at which a defensive special applies
#	- value: fraction by which a defensive special reduces damage (currently the only effect for defensive specials)
#	- effect:
#		- multiplier: damage multiplier (value = multiplier value)
#		- boostbystat: damage boost of (value * stat)
#		- absorb: absorb fraction of damage dealt equal to value
#		- pierce: pierce fraction of enemy defenses equal to value
#		- aether: combine effects of absorb and pierce
#		- vengeance: damage boost of (value * damage taken)
# trianglebonus: Additional multiplier for triangle advantage
# negateselfaffinity: Negate trianglebonus of other skills this unit has
# negateenemyaffinity: Negate trianglebonus of skills the enemy has when the enemy is at an advantage
# negateenemydisaffinity: Negate trianglebonus of skills the enemy has when the enemy is at a disadvantage
# reverseenemyaffinity: Reverse trianglebonus of skills the enemy has when the enemy is at an advantage
# effective: Indicates a movement type or weapon type to gain a 1.5x attack bonus against
# shield: Prevents enemy 'effective' skills
# wrath: Override weapon modifiers (Wrathful Staff)
# absorb: Absorb fraction of damage dealt equal to value
# miracle: Survive a lethal blow with 1 HP remaining if special is charged
# heavy: Gain bonus charge on each attack
#	- stat: effective stat (with combat spurs, etc.) that must be greater than opponent's
#	- margin: margin by which the effective stat must be greater
#	- value: bonus charge gained on attack if conditions are met
# guard: Reduce the charge opponent builds by the given value
# anyrangecounter: Counter attacks from any range
# vantage: Counterattack before an enemy's attack
# desperation: Follow-up attacks occur immediately after initial attack
# autofollow: Automatically trigger a follow-up attack
# noselffollow: Prevent follow-up attacks by this unit
# noenemyfollow: Prevent enemy follow-up attacks
# noselfcounter: Prevent counter-attacks by this unit
# noenemycounter: Prevent enemy counter-attacks
# brash: Gain an automatic follow-up attack when below a certain HP threshold and attacking an enemy that can counter
# brave: Attack twice consecutively when initiating combat
# galeforce: Initiate again if special is charged
# condition: Condition that must be met for skill to activate
#####

#####
# CONDITION TYPES
# hpmax: Check that the unit's HP is at or below a certain percentage
# - value = the threshold percentage
# hpmin: Check that the unit's HP is at or above a certain percentage
# - value = the threshold percentage
# hpstartmin: Check that the unit's HP was at or above a certain percentage at start of combat
# - value = the threshold percentage
# statcomp: Check that the unit's stat value is a certain margin above the enemy's
# - stat = stat to compare
# - margin = amount by which the user's value must be greater than the enemy's
# init: Check that the unit initiated this round of combat
# def: Check that the unit is defending this round of combat
# rangeddef: Check that the unit is defending against a ranged attacker
# meleedef: Check that the unit is defending against a melee attacker
# echo: Check conditions for Ragnarok-style weapons
# 	These have three components:
#	1. If the unit is at full health, grant the spur bonus
# 	2. If the unit started combat at full health and made an attack, trigger fury
# 	3. If the unit made an attack, trigger the Seashell's usual dagger effect
# chivalry: Check that the enemy's HP is at or above a certain percentage
# - value = the threshold percentage
# adjacency: Skills that vary based on adjacent allies, handled in skill setup
# didattack: Check that the unit made an attack
# attackedclass: Check that the unit attacked an enemy of a certain movetype
# - value = the move type of the enemy to check
# breaker: Check that the unit meets conditions for breaker skills
# - weapon = the type of the weapon the enemy must have
# - value = the minimum percentage of HP the unit must be at
# riposte: Check that the unit is defending and at a minimum HP percentage
# - value = the threshold HP percentage
# sweep: Check conditions for sweep skills (Windsweep/Watersweep)
#	These have two components:
#	1. If the unit is attacking, prevent the unit from making a followup attack
#	2. Prevent the enemy from countering if the enemy attack type is right and the speed margin is met
# - attacktype = the attack type (magical/physical) that the enemy must have
# - stat = stat to compare for whether the enemy can counter
# - margin = necessary stat margin to prevent the enemy from countering
# defensivespecial: Check that the unit has a defensive special
#####

skillList = {
	"Iron Sword":{
		"slot":"weapon",
		"sp":0,
		"atk":6,
		"inheritrule":"sword",
		"affectsduel":1,
	},
	"Steel Sword":{
		"slot":"weapon",
		"sp":100,
		"atk":8,
		"inheritrule":"sword",
		"affectsduel":1,
	},
	"Silver Sword":{
		"slot":"weapon",
		"sp":200,
		"atk":11,
		"inheritrule":"sword",
		"affectsduel":1,
	},
	"Silver Sword+":{
		"slot":"weapon",
		"sp":300,
		"atk":15,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
	},
	"Armorslayer":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"sword",
		"affectsduel":1,
		"effective":"armored",
	},
	"Armorslayer+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"effective":"armored",
	},
	"Brave Sword":{
		"slot":"weapon",
		"sp":200,
		"atk":5,
		"spd":-5,
		"inheritrule":"sword",
		"affectsduel":1,
		"brave":1,
	},
	"Brave Sword+":{
		"slot":"weapon",
		"sp":300,
		"atk":8,
		"spd":-5,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"brave":1,
	},
	"Killing Edge":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"charge":1,
		"inheritrule":"sword",
		"affectsduel":1,
	},
	"Killing Edge+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"charge":1,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
	},
	"Ruby Sword":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"charge":0,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":0,
		"trianglebonus":.2
	},
	"Ruby Sword+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"trianglebonus":.2
	},
	"Wo Dao":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"sword",
		"affectsduel":1,
		"specialboost":10
	},
	"Wo Dao+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"specialboost":10
	},
	"Binding Blade":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":2, "res":2},
		"condition":{"type":"def"},
	},
	"Durandal":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":4},
		"condition":{"type":"init"},
	},
	"Falchion":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"turnstotrigger":3,
		"triggereffect":{"type":"renew", "value":10},
		"affectsduel":1,
		"ismax":1,
		"effective":"dragon",
	},
	"Folkvangr":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"buff":{"atk":5},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Mystletainn":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"charge":1,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Raijinto":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Sieglinde":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Sol Katti":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"desperation":1,
		"condition":{"type":"hpmax", "value":.5},
	},
	"Tyrfing":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":4},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Yato":{
		"name":"Yato",
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"spd":4},
		"condition":{"type":"init"},
	},
	"Fire":{
		"slot":"weapon",
		"sp":0,
		"atk":4,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Elfire":{
		"slot":"weapon",
		"sp":100,
		"atk":6,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Bolganone":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Bolganone+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
	},
	"Flux":{
		"slot":"weapon",
		"sp":0,
		"atk":4,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Ruin":{
		"slot":"weapon",
		"sp":100,
		"atk":6,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Fenrir":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"redtome",
		"affectsduel":1,
	},
	"Fenrir+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
	},
	"Raudrblade":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"charge":-1,
		"inheritrule":"redtome",
		"affectsduel":1,
		"blade":1,
	},
	"Raudrblade+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"charge":-1,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
		"blade":1
	},
	"Raudrraven":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"redtome",
		"affectsduel":1,
		"advantage":"gray"
	},
	"Raudrraven+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
		"advantage":"gray"
	},
	"Raudrwolf":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"redtome",
		"affectsduel":1,
		"effective":"cavalry",
	},
	"Raudrwolf+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
		"effective":"cavalry",
	},
	"Brynhildr":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Cymbeline":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Iron Axe":{
		"slot":"weapon",
		"sp":0,
		"atk":6,
		"inheritrule":"axe",
		"affectsduel":1,
	},
	"Steel Axe":{
		"slot":"weapon",
		"sp":100,
		"atk":8,
		"inheritrule":"axe",
		"affectsduel":1,
	},
	"Silver Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":11,
		"inheritrule":"axe",
		"affectsduel":1,
	},
	"Silver Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":15,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
	},
	"Brave Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":5,
		"spd":-5,
		"inheritrule":"axe",
		"affectsduel":1,
		"brave":1,
	},
	"Brave Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":8,
		"spd":-5,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"brave":1,
	},
	"Emerald Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"axe",
		"affectsduel":1,
		"trianglebonus":.2
	},
	"Emerald Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"trianglebonus":.2
	},
	"Hammer":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"axe",
		"affectsduel":1,
		"effective":"armored",
	},
	"Hammer+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"effective":"armored",
	},
	"Killer Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"charge":1,
		"inheritrule":"axe",
		"affectsduel":1,
	},
	"Killer Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"charge":1,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
	},
	"Armads":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"condition":{"type":"riposte", "value":.8},
	},
	"Hauteclere":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"charge":1,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Noatun":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Wind":{
		"slot":"weapon",
		"sp":0,
		"atk":4,
		"inheritrule":"greentome",
		"affectsduel":1,
	},
	"Elwind":{
		"slot":"weapon",
		"sp":100,
		"atk":6,
		"inheritrule":"greentome",
		"affectsduel":1,
	},
	"Rexcalibur":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"greentome",
		"affectsduel":1,
	},
	"Gronnblade":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"charge":-1,
		"inheritrule":"greentome",
		"affectsduel":1,
		"blade":1,
	},
	"Gronnblade+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"charge":-1,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"blade":1
	},
	"Gronnraven":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"greentome",
		"affectsduel":1,
		"advantage":"gray"
	},
	"Gronnraven+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"advantage":"gray"
	},
	"Gronnwolf":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"greentome",
		"affectsduel":1,
		"effective":"cavalry",
	},
	"Gronnwolf+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"effective":"cavalry",
	},
	"Excalibur":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Naga":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":2, "res":2},
		"condition":{"type":"def"},
		"effective":"dragon",
	},
	"Iron Lance":{
		"slot":"weapon",
		"sp":0,
		"atk":6,
		"inheritrule":"lance",
		"affectsduel":1,
	},
	"Steel Lance":{
		"slot":"weapon",
		"sp":100,
		"atk":8,
		"inheritrule":"lance",
		"affectsduel":1,
	},
	"Silver Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":11,
		"inheritrule":"lance",
		"affectsduel":1,
	},
	"Silver Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":15,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
	},
	"Brave Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":5,
		"spd":-5,
		"inheritrule":"lance",
		"affectsduel":1,
		"brave":1,
	},
	"Brave Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":8,
		"spd":-5,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"brave":1,
	},
	"Heavy Spear":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"lance",
		"affectsduel":1,
		"effective":"armored",
	},
	"Heavy Spear+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"effective":"armored",
	},
	"Killer Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"charge":1,
		"inheritrule":"lance",
		"affectsduel":1,
	},
	"Killer Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"charge":1,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
	},
	"Sapphire Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"lance",
		"affectsduel":1,
		"trianglebonus":.2
	},
	"Sapphire Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"trianglebonus":.2
	},
	"Fensalir":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"atk":-4},
	},
	"Siegmund":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Thunder":{
		"slot":"weapon",
		"sp":0,
		"atk":4,
		"inheritrule":"bluetome",
		"affectsduel":1,
	},
	"Elthunder":{
		"slot":"weapon",
		"sp":100,
		"atk":6,
		"inheritrule":"bluetome",
		"affectsduel":1,
	},
	"Thoron":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"bluetome",
		"affectsduel":1,
	},
	"Blarblade":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"charge":-1,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"blade":1,
	},
	"Blarblade+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"charge":-1,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"blade":1
	},
	"Blarwolf":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"effective":"cavalry",
	},
	"Blarwolf+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"effective":"cavalry",
	},
	"Blarraven":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"advantage":"gray"
	},
	"Blarraven+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"advantage":"gray"
	},
	"Dire Thunder":{
		"slot":"weapon",
		"sp":400,
		"atk":9,
		"spd":-5,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"brave":1,
	},
	"Aura":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
	},
	"Fire Breath":{
		"slot":"weapon",
		"sp":0,
		"atk":6,
		"inheritrule":"dragon",
		"affectsduel":1,
	},
	"Fire Breath+":{
		"slot":"weapon",
		"sp":100,
		"atk":8,
		"inheritrule":"dragon",
		"affectsduel":1,
	},
	"Flametongue":{
		"slot":"weapon",
		"sp":200,
		"atk":11,
		"inheritrule":"dragon",
		"affectsduel":1,
	},
	"Flametongue+":{
		"slot":"weapon",
		"sp":300,
		"atk":15,
		"inheritrule":"dragon",
		"affectsduel":1,
		"ismax":1,
	},
	"Lightning Breath":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"charge":-1,
		"inheritrule":"dragon",
		"affectsduel":1,
		"anyrangecounter":1,
	},
	"Lightning Breath+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"charge":-1,
		"inheritrule":"dragon",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Light Breath":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"dragon",
		"affectsduel":1,
	},
	"Light Breath+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"dragon",
		"affectsduel":1,
		"ismax":1,
	},
	"Dark Breath":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"dragon",
		"affectsduel":1,
	},
	"Dark Breath+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"dragon",
		"affectsduel":1,
		"ismax":1,
	},
	"Iron Bow":{
		"slot":"weapon",
		"sp":0,
		"atk":4,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Steel Bow":{
		"slot":"weapon",
		"sp":100,
		"atk":6,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Silver Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Silver Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Assassin's Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":0, "weapon":"dagger"},
	},
	"Assassin's Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":0, "weapon":"dagger"},
	},
	"Brave Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":4,
		"spd":-5,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
		"brave":1,
	},
	"Brave Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":7,
		"spd":-5,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
		"brave":1,
	},
	"Killer Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":5,
		"charge":1,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Killer Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":9,
		"charge":1,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Fujin Yumi":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Parthia":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"res":4},
		"condition":{"type":"init"},
		"effective":"flying",
	},
	"Iron Dagger":{
		"slot":"weapon",
		"sp":0,
		"atk":3,
		"inheritrule":"dagger",
		"affectsduel":1,
		"seal":{"def":-3, "res":-3},
		"condition":{"type":"didattack"},
	},
	"Steel Dagger":{
		"slot":"weapon",
		"sp":100,
		"atk":5,
		"inheritrule":"dagger",
		"affectsduel":1,
		"seal":{"def":-3, "res":-3},
		"condition":{"type":"didattack"},
	},
	"Silver Dagger":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"dagger",
		"affectsduel":1,
		"seal":{"def":-5, "res":-5},
		"condition":{"type":"didattack"},
	},
	"Silver Dagger+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"dagger",
		"affectsduel":1,
		"ismax":1,
		"seal":{"def":-7, "res":-7},
		"condition":{"type":"didattack"},
	},
	"Poison Dagger":{
		"slot":"weapon",
		"sp":200,
		"atk":2,
		"inheritrule":"dagger",
		"affectsduel":1,
		"seal":{"def":-4, "res":-4},
		"condition":{"type":"attackedclass", "value":"infantry"},
		"effective":"infantry",
	},
	"Poison Dagger+":{
		"slot":"weapon",
		"sp":300,
		"atk":5,
		"inheritrule":"dagger",
		"affectsduel":1,
		"ismax":1,
		"seal":{"def":-6, "res":-6},
		"condition":{"type":"attackedclass", "value":"infantry"},
		"effective":"infantry",
	},
	"Rogue Dagger":{
		"slot":"weapon",
		"sp":200,
		"atk":4,
		"inheritrule":"dagger",
		"affectsduel":1,
		"seal":{"def":-3, "res":-3},
		"postbuff":{"def":3, "res":3},
		"condition":{"type":"didattack"},
	},
	"Rogue Dagger+":{
		"slot":"weapon",
		"sp":300,
		"atk":7,
		"inheritrule":"dagger",
		"affectsduel":1,
		"ismax":1,
		"seal":{"def":-5, "res":-5},
		"postbuff":{"def":5, "res":5},
		"condition":{"type":"didattack"},
	},
	"Smoke Dagger":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"dagger",
		"affectsduel":1,
	},
	"Smoke Dagger+":{
		"slot":"weapon",
		"sp":300,
		"atk":9,
		"inheritrule":"dagger",
		"affectsduel":1,
		"ismax":1,
	},
	"Deathly Dagger":{
		"slot":"weapon",
		"sp":400,
		"atk":11,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"poison":7
	},
	"Assault":{
		"slot":"weapon",
		"sp":50,
		"atk":10,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
	},
	"Absorb":{
		"slot":"weapon",
		"sp":150,
		"atk":4,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"absorb":.5,
	},
	"Fear":{
		"slot":"weapon",
		"sp":150,
		"atk":5,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"atk":-6},
		"condition":{"type":"didattack"},
	},
	"Gravity":{
		"slot":"weapon",
		"sp":150,
		"atk":6,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Pain":{
		"slot":"weapon",
		"sp":150,
		"atk":3,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"pain":10,
	},
	"Panic":{
		"slot":"weapon",
		"sp":150,
		"atk":7,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"panic":1},
	},
	"Slow":{
		"slot":"weapon",
		"sp":150,
		"atk":5,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"spd":-6},
		"condition":{"type":"didattack"},
	},
	"Night Sky":{
		"slot":"special",
		"sp":100,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense", 
			"effect":"multiplier", 
			"value":1.5
		},
	},
	"Dragon Gaze":{
		"slot":"special",
		"sp":100,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"atk", 
			"value":.3
		},
	},
	"Glowing Ember":{
		"slot":"special",
		"sp":100,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"def", 
			"value":.5
		},
	},
	"Daylight":{
		"slot":"special",
		"sp":100,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense",
			"effect":"absorb",
			"value":.3
		},
	},
	"New Moon":{
		"slot":"special",
		"sp":100,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense",
			"effect":"pierce",
			"value":.3
		},
	},
	"Chilling Wind":{
		"slot":"special",
		"sp":100,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"res", 
			"value":.5
		},
	},
	"Retribution":{
		"slot":"special",
		"sp":100,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{
			"type":"offense",
			"effect":"vengeance",
			"value":.3
		},
	},
	"Glimmer":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"multiplier", 
			"value":1.5
		},
	},
	"Astra":{
		"slot":"special",
		"sp":200,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"multiplier", 
			"value":2.5
		},
	},
	"Draconic Aura":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"atk", 
			"value":.3
		},
	},
	"Dragon Fang":{
		"slot":"special",
		"sp":200,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"atk", 
			"value":.5
		},
	},
	"Bonfire":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"def", 
			"value":.5
		},
	},
	"Ignis":{
		"slot":"special",
		"sp":200,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"def", 
			"value":.8
		},
	},
	"Noontime":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"absorb",
			"value":.3
		},
	},
	"Sol":{
		"slot":"special",
		"sp":200,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"absorb",
			"value":.5
		},
	},
	"Moonbow":{
		"slot":"special",
		"sp":200,
		"charge":2,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"pierce",
			"value":.3
		},
	},
	"Luna":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"pierce",
			"value":.5
		},
	},
	"Iceberg":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"res", 
			"value":.5
		},
	},
	"Glacies":{
		"slot":"special",
		"sp":200,
		"charge":4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense", 
			"effect":"boostbystat", 
			"stat":"res", 
			"value":.8
		},
	},
	"Reprisal":{
		"slot":"special",
		"sp":200,
		"charge":2,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"vengeance",
			"value":.3
		},
	},
	"Vengeance":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"vengeance",
			"value":.5
		},
	},
	"Galeforce":{
		"slot":"special",
		"sp":500,
		"charge":5,
		"inheritrule":"melee,physical",
		"affectsduel":1,
		"ismax":1,
		"galeforce":1,
	},
	"Aether":{
		"slot":"special",
		"sp":500,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"offense",
			"effect":"aether",
			"value":.5
		},
	},
	"Rising Thunder":{
		"slot":"special",
		"sp":150,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Rising Wind":{
		"slot":"special",
		"sp":150,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Rising Light":{
		"slot":"special",
		"sp":150,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Rising Flame":{
		"slot":"special",
		"sp":150,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Growing Thunder":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Blazing Thunder":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1.5},
	},
	"Growing Wind":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Blazing Wind":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1.5},
	},
	"Growing Light":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Blazing Light":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1.5},
	},
	"Growing Flame":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1},
	},
	"Blazing Flame":{
		"slot":"special",
		"sp":300,
		"charge":5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"special":{"type":"AOE", "multiplier":1.5},
	},
	"Buckler":{
		"slot":"special",
		"sp":100,
		"charge":3,
		"inheritrule":"melee",
		"affectsduel":1,
		"special":{
			"type":"defense",
			"range":"melee",
			"value":.3
		},
	},
	"Holy Vestments":{
		"slot":"special",
		"sp":100,
		"charge":3,
		"inheritrule":"melee",
		"affectsduel":1,
		"special":{
			"type":"defense",
			"range":"ranged",
			"value":.3
		},
	},
	"Escutcheon":{
		"slot":"special",
		"sp":200,
		"charge":2,
		"inheritrule":"melee",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"defense",
			"range":"melee",
			"value":.3
		},
	},
	"Pavise":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"melee",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"defense",
			"range":"melee",
			"value":.5
		},
	},
	"Sacred Cowl":{
		"slot":"special",
		"sp":200,
		"charge":2,
		"inheritrule":"melee",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"defense",
			"range":"ranged",
			"value":.3
		},
	},
	"Aegis":{
		"slot":"special",
		"sp":200,
		"charge":3,
		"inheritrule":"melee",
		"affectsduel":1,
		"ismax":1,
		"special":{
			"type":"defense",
			"range":"ranged",
			"value":.5
		},
	},
	"Imbue":{
		"slot":"special",
		"sp":50,
		"charge":1,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Heavenly Light":{
		"slot":"special",
		"sp":150,
		"charge":2,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Kindled-Fire Balm":{
		"slot":"special",
		"sp":150,
		"charge":1,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Swift-Winds Balm":{
		"slot":"special",
		"sp":150,
		"charge":1,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Solid-Earth Balm":{
		"slot":"special",
		"sp":150,
		"charge":1,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Still-Water Balm":{
		"slot":"special",
		"sp":150,
		"charge":1,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Miracle":{
		"slot":"special",
		"sp":200,
		"charge":5,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"miracle":1,
		"special":{"type":"defense", "range":"miracle"},
	},
	"HP 3":{
		"slot":"a",
		"sp":30,
		"hp":3,
		"inheritrule":"",
		"affectsduel":1,
	},
	"HP 4":{
		"slot":"a",
		"sp":60,
		"hp":4,
		"inheritrule":"",
		"affectsduel":1,
	},
	"HP 5":{
		"slot":"a",
		"sp":120,
		"hp":5,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Attack 1":{
		"slot":"a",
		"sp":30,
		"atk":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Attack 2":{
		"slot":"a",
		"sp":60,
		"atk":2,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Attack 3":{
		"slot":"a",
		"sp":120,
		"atk":3,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Speed 1":{
		"slot":"a",
		"sp":30,
		"spd":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Speed 2":{
		"slot":"a",
		"sp":60,
		"spd":2,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Speed 3":{
		"slot":"a",
		"sp":120,
		"spd":3,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Defense 1":{
		"slot":"a",
		"sp":30,
		"def":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Defense 2":{
		"slot":"a",
		"sp":60,
		"def":2,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Defense 3":{
		"slot":"a",
		"sp":120,
		"def":3,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Resistance 1":{
		"slot":"a",
		"sp":30,
		"res":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Resistance 2":{
		"slot":"a",
		"sp":60,
		"res":2,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Resistance 3":{
		"slot":"a",
		"sp":120,
		"res":3,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Fury 1":{
		"slot":"a",
		"sp":50,
		"atk":1,
		"spd":1,
		"def":1,
		"res":1,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"fury":2	
	},
	"Fury 2":{
		"slot":"a",
		"sp":100,
		"atk":2,
		"spd":2,
		"def":2,
		"res":2,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"fury":4
	},
	"Fury 3":{
		"slot":"a",
		"sp":200,
		"atk":3,
		"spd":3,
		"def":3,
		"res":3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"fury":6
	},
	"Life and Death 1":{
		"slot":"a",
		"sp":50,
		"atk":3,
		"spd":3,
		"def":-3,
		"res":-3,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
	},
	"Life and Death 2":{
		"slot":"a",
		"sp":100,
		"atk":4,
		"spd":4,
		"def":-4,
		"res":-4,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
	},
	"Life and Death 3":{
		"slot":"a",
		"sp":200,
		"atk":5,
		"spd":5,
		"def":-5,
		"res":-5,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
	},
	"Armored Blow 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"def":2},
		"condition":{"type":"init"},
	},
	"Armored Blow 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"def":4},
		"condition":{"type":"init"},
	},
	"Armored Blow 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":6},
		"condition":{"type":"init"},
	},
	"Darting Blow 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"spd":2},
		"condition":{"type":"init"},
	},
	"Darting Blow 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"spd":4},
		"condition":{"type":"init"},
	},
	"Darting Blow 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"spd":6},
		"condition":{"type":"init"},
	},
	"Death Blow 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"atk":2},
		"condition":{"type":"init"},
	},
	"Death Blow 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"atk":4},
		"condition":{"type":"init"},
	},
	"Death Blow 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":6},
		"condition":{"type":"init"},
	},
	"Warding Blow 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"res":2},
		"condition":{"type":"init"},
	},
	"Warding Blow 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"res":4},
		"condition":{"type":"init"},
	},
	"Warding Blow 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"res":6},
		"condition":{"type":"init"},
	},
	"Defiant Atk 1":{
		"slot":"a",
		"sp":40,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"atk":3},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Atk 2":{
		"slot":"a",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"atk":5},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Atk 3":{
		"slot":"a",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"buff":{"atk":7},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Spd 1":{
		"slot":"a",
		"sp":40,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"spd":3},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Spd 2":{
		"slot":"a",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"spd":5},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Spd 3":{
		"slot":"a",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"buff":{"spd":7},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Def 1":{
		"slot":"a",
		"sp":40,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"def":3},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Def 2":{
		"slot":"a",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"def":5},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Def 3":{
		"slot":"a",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"buff":{"def":7},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Res 1":{
		"slot":"a",
		"sp":40,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"res":3},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Res 2":{
		"slot":"a",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"buff":{"res":5},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Defiant Res 3":{
		"slot":"a",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"buff":{"res":7},
		"condition":{"type":"hpmax", "value":.5},
	},
	"Triangle Adept 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"nongray",
		"affectsduel":1,
		"trianglebonus":.1,
	},
	"Triangle Adept 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"nongray",
		"affectsduel":1,
		"trianglebonus":.15,
	},
	"Triangle Adept 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"nongray",
		"affectsduel":1,
		"ismax":1,
		"trianglebonus":.2
	},
	"Close Counter":{
		"slot":"a",
		"sp":300,
		"inheritrule":"ranged",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Distant Counter":{
		"slot":"a",
		"sp":300,
		"inheritrule":"melee",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1
	},
	"Svalinn Shield":{
		"slot":"a",
		"sp":200,
		"inheritrule":"armored",
		"affectsduel":1,
		"ismax":1,
		"shield":1,
	},
	"Seal Atk 1":{
		"slot":"b",
		"sp":40,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"atk":-3},
	},
	"Seal Atk 2":{
		"slot":"b",
		"sp":80,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"atk":-5},
	},
	"Seal Atk 3":{
		"slot":"b",
		"sp":160,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"atk":-7},
	},
	"Seal Spd 1":{
		"slot":"b",
		"sp":40,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"spd":-3},
	},
	"Seal Spd 2":{
		"slot":"b",
		"sp":80,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"spd":-5},
	},
	"Seal Spd 3":{
		"slot":"b",
		"sp":160,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"spd":-7},
	},
	"Seal Def 1":{
		"slot":"b",
		"sp":40,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"def":-3},
	},
	"Seal Def 2":{
		"slot":"b",
		"sp":80,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"def":-5},
	},
	"Seal Def 3":{
		"slot":"b",
		"sp":160,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"def":-7},
	},
	"Seal Res 1":{
		"slot":"b",
		"sp":40,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"res":-3},
	},
	"Seal Res 2":{
		"slot":"b",
		"sp":80,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"seal":{"res":-5},
	},
	"Seal Res 3":{
		"slot":"b",
		"sp":160,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"res":-7},
	},
	"Escape Route 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"",
	},
	"Escape Route 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"",
	},
	"Escape Route 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"",
		"ismax":1,
	},
	"Wings of Mercy 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"",
	},
	"Wings of Mercy 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"",
	},
	"Wings of Mercy 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"",
		"ismax":1,
	},
	"Pass 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
	},
	"Pass 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
	},
	"Pass 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Obstruct 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
	},
	"Obstruct 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
	},
	"Obstruct 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Wary Fighter 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"armored",
		"affectsduel":1,
		"noselffollow":1,
		"noenemyfollow":1,
		"condition":{"type":"hpmin", "value":.9},
	},
	"Wary Fighter 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"armored",
		"affectsduel":1,
		"noselffollow":1,
		"noenemyfollow":1,
		"condition":{"type":"hpmin", "value":.7},
	},
	"Wary Fighter 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"armored",
		"affectsduel":1,
		"ismax":1,
		"noselffollow":1,
		"noenemyfollow":1,
		"condition":{"type":"hpmin", "value":.5},
	},
	"Vantage 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"vantage":1,
		"condition":{"type":"hpmax", "value":.25},
	},
	"Vantage 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"vantage":1,
		"condition":{"type":"hpmax", "value":.5},
	},
	"Vantage 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"vantage":1,
		"condition":{"type":"hpmax", "value":.75},
	},
	"Quick Riposte 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"autofollow":1,
		"condition":{"type":"riposte", "value":.9},
	},
	"Quick Riposte 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"autofollow":1,
		"condition":{"type":"riposte", "value":.8},
	},
	"Quick Riposte 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"condition":{"type":"riposte", "value":.7},
	},
	"Desperation 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"desperation":1,
		"condition":{"type":"hpmax", "value":.25},
	},
	"Desperation 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"desperation":1,
		"condition":{"type":"hpmax", "value":.5},
	},
	"Desperation 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"desperation":1,
		"condition":{"type":"hpmax", "value":.75},
	},
	"Brash Assault 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"brash":1,
		"condition":{"type":"hpmax", "value":.3},
	},
	"Brash Assault 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"brash":1,
		"condition":{"type":"hpmax", "value":.4},
	},
	"Brash Assault 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"brash":1,
		"condition":{"type":"hpmax", "value":.5},
	},
	"Poison Strike 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"poison":4
	},
	"Poison Strike 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"poison":7
	},
	"Poison Strike 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"poison":10
	},
	"Renewal 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"",
		"turnstotrigger":4,
		"triggereffect":{"type":"renew", "value":10},
		"affectsduel":1,
	},
	"Renewal 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"",
		"turnstotrigger":3,
		"triggereffect":{"type":"renew", "value":10},
		"affectsduel":1,
	},
	"Renewal 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"",
		"turnstotrigger":2,
		"triggereffect":{"type":"renew", "value":10},
		"affectsduel":1,
		"ismax":1,
	},
	"Live to Serve 1":{
		"slot":"b",
		"sp":40,
		"inheritrule":"staff",
	},
	"Live to Serve 2":{
		"slot":"b",
		"sp":80,
		"inheritrule":"staff",
	},
	"Live to Serve 3":{
		"slot":"b",
		"sp":160,
		"inheritrule":"staff",
		"ismax":1,
	},
	"Swordbreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"sword"},
	},
	"Swordbreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"sword"},
	},
	"Swordbreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"sword"},
	},
	"Axebreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"axe"},
	},
	"Axebreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"axe"},
	},
	"Axebreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"axe"},
	},
	"Lancebreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonred",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"lance"},
	},
	"Lancebreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonred",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"lance"},
	},
	"Lancebreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonred",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"lance"},
	},
	"B Tomebreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonred",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"bluetome"},
	},
	"B Tomebreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonred",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"bluetome"},
	},
	"B Tomebreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonred",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"bluetome"},
	},
	"G Tomebreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"greentome"},
	},
	"G Tomebreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"greentome"},
	},
	"G Tomebreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonblue",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"greentome"},
	},
	"R Tomebreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"redtome"},
	},
	"R Tomebreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"redtome"},
	},
	"R Tomebreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nongreen",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"redtome"},
	},
	"Bowbreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonflying",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"bow"},
	},
	"Bowbreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonflying",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"bow"},
	},
	"Bowbreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonflying",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"bow"},
	},
	"Daggerbreaker 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.9, "weapon":"dagger"},
	},
	"Daggerbreaker 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.7, "weapon":"dagger"},
	},
	"Daggerbreaker 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"autofollow":1,
		"noenemyfollow":1,
		"condition":{"type":"breaker", "value":.5, "weapon":"dagger"},
	},
	"Lunge":{
		"slot":"b",
		"sp":150,
		"inheritrule":"melee",
		"ismax":1,
	},
	"Knock Back":{
		"slot":"b",
		"sp":150,
		"inheritrule":"melee",
		"ismax":1,
	},
	"Drag Back":{
		"slot":"b",
		"sp":150,
		"inheritrule":"melee",
		"ismax":1,
	},
	"Hone Atk 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Hone Atk 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Hone Atk 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Hone Spd 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Hone Spd 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Hone Spd 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Fortify Def 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Fortify Def 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Fortify Def 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Fortify Res 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Fortify Res 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Fortify Res 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Spur Atk 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Spur Atk 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Spur Atk 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Spur Spd 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Spur Spd 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Spur Spd 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Spur Def 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Spur Def 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Spur Def 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Spur Res 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Spur Res 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Spur Res 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Threaten Atk 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"atk":-3},
	},
	"Threaten Atk 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"atk":-4},
	},
	"Threaten Atk 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"atk":-5},
	},
	"Threaten Spd 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"spd":-3},
	},
	"Threaten Spd 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"spd":-4},
	},
	"Threaten Spd 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"spd":-5},
	},
	"Threaten Def 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"def":-3},
	},
	"Threaten Def 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"def":-4},
	},
	"Threaten Def 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"def":-5},
	},
	"Threaten Res 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"res":-3},
	},
	"Threaten Res 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"threaten":{"res":-4},
	},
	"Threaten Res 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"res":-5},
	},
	"Savage Blow 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Savage Blow 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Savage Blow 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Breath of Life 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"",
	},
	"Breath of Life 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"",
	},
	"Breath of Life 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"",
		"ismax":1,
	},
	"Hone Armor":{
		"slot":"c",
		"sp":200,
		"inheritrule":"armored",
		"ismax":1,
	},
	"Fortify Armor":{
		"slot":"c",
		"sp":200,
		"inheritrule":"armored",
		"ismax":1,
	},
	"Goad Armor":{
		"slot":"c",
		"sp":200,
		"inheritrule":"armored",
		"ismax":1,
	},
	"Ward Armor":{
		"slot":"c",
		"sp":200,
		"inheritrule":"armored",
		"ismax":1,
	},
	"Hone Fliers":{
		"slot":"c",
		"sp":200,
		"inheritrule":"flying",
		"ismax":1,
	},
	"Fortify Fliers":{
		"slot":"c",
		"sp":200,
		"inheritrule":"flying",
		"ismax":1,
	},
	"Goad Fliers":{
		"slot":"c",
		"sp":200,
		"inheritrule":"flying",
		"ismax":1,
	},
	"Ward Fliers":{
		"slot":"c",
		"sp":200,
		"inheritrule":"flying",
		"ismax":1,
	},
	"Hone Cavalry":{
		"slot":"c",
		"sp":200,
		"inheritrule":"cavalry",
		"ismax":1,
	},
	"Fortify Cavalry":{
		"slot":"c",
		"sp":200,
		"inheritrule":"cavalry",
		"ismax":1,
	},
	"Goad Cavalry":{
		"slot":"c",
		"sp":200,
		"inheritrule":"cavalry",
		"ismax":1,
	},
	"Ward Cavalry":{
		"slot":"c",
		"sp":200,
		"inheritrule":"cavalry",
		"ismax":1,
	},
	"Fortify Dragons":{
		"slot":"c",
		"sp":200,
		"inheritrule":"dragon",
		"ismax":1,
	},
	"Iote's Shield":{
		"slot":"a",
		"sp":200,
		"inheritrule":"flying",
		"affectsduel":1,
		"ismax":1,
		"shield":1,
	},
	"Swift Sparrow 1":{
		"slot":"a",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"atk":2, "spd":2},
		"condition":{"type":"init"},
	},
	"Swift Sparrow 2":{
		"slot":"a",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":4, "spd":4},
		"condition":{"type":"init"},
	},
	"Carrot Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"lance",
		"affectsduel":1,
		"postheal":4,
	},
	"Carrot Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"postheal":4,
	},
	"Carrot Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"axe",
		"affectsduel":1,
		"postheal":4,
	},
	"Carrot Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"postheal":4,
	},
	"Blue Egg":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"postheal":4,
	},
	"Blue Egg+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"postheal":4,
	},
	"Green Egg":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"greentome",
		"affectsduel":1,
		"postheal":4,
	},
	"Green Egg+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"postheal":4,
	},
	"Attack Def 1":{
		"slot":"a",
		"sp":30,
		"atk":1,
		"def":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Attack Def 2":{
		"slot":"a",
		"sp":60,
		"atk":2,
		"def":2,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Axe Experience 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"axe",
	},
	"Axe Experience 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"axe",
	},
	"Axe Experience 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"axe",
		"ismax":1,
	},
	"Live for Honor":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"ismax":1,
	},
	"Live for Bounty":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"ismax":1,
	},
	"Attack 1 (Seal)":{
		"slot":"s",
		"sp":0,
		"atk":1,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Speed 1 (Seal)":{
		"slot":"s",
		"sp":0,
		"spd":1,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"HP 3 (Seal)":{
		"slot":"s",
		"sp":0,
		"hp":3,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Windsweep 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"physical",
			"stat":"spd",
			"margin":5,
		},
	},
	"Windsweep 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"physical",
			"stat":"spd",
			"margin":3,
		},
	},
	"Windsweep 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"physical",
			"stat":"spd",
			"margin":1,
		},
	},
	"Hit and Run":{
		"slot":"b",
		"sp":150,
		"inheritrule":"melee",
		"ismax":1,
	},
	"Fortress Def 1":{
		"slot":"a",
		"sp":50,
		"atk":-3,
		"def":3,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Fortress Def 2":{
		"slot":"a",
		"sp":100,
		"atk":-3,
		"def":4,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Fortress Def 3":{
		"slot":"a",
		"sp":200,
		"atk":-3,
		"def":5,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Firesweep Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
		"noselfcounter":1,
		"noenemycounter":1,
	},
	"Firesweep Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
		"noselfcounter":1,
		"noenemycounter":1,
	},
	"Bow Experience 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"bow",
	},
	"Bow Experience 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"bow",
	},
	"Bow Experience 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"bow",
		"ismax":1,
	},
	"Eckesachs":{
		"slot":"weapon",
		"sp":300,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"threaten":{"def":-4},
	},
	"Ragnell":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Heavy Blade 1":{
		"slot":"a",
		"sp":60,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"heavy":{"stat":"atk", "margin":5, "value":1},
	},
	"Heavy Blade 2":{
		"slot":"a",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"heavy":{"stat":"atk", "margin":3, "value":1},
	},
	"Heavy Blade 3":{
		"slot":"a",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"heavy":{"stat":"atk", "margin":1, "value":1},
	},
	"Spur Def Res 1":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
	},
	"Spur Def Res 2":{
		"slot":"c",
		"sp":240,
		"inheritrule":"",
		"ismax":1,
	},
	"Rexcalibur+":{
		"slot":"weapon",
		"sp":300,
		"atk":13,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
	},
	"Guard 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"guard":1,
		"condition":{"type":"hpstartmin", "value":1},
	},
	"Guard 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"guard":1,
		"condition":{"type":"hpstartmin", "value":.9},
	},
	"Guard 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"guard":1,
		"condition":{"type":"hpstartmin", "value":.8},
	},
	"Watersweep 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"magical",
			"stat":"spd",
			"margin":5,
		},
	},
	"Watersweep 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"magical",
			"stat":"spd",
			"margin":3,
		},
	},
	"Watersweep 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"noenemycounter":1,
		"noselffollow":1,
		"condition":{
			"type":"sweep",
			"attacktype":"magical",
			"stat":"spd",
			"margin":1,
		},
	},
	"Siegfried":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Gronnowl":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"greentome",
		"affectsduel":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"Gronnowl+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"Earth Boost 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":2},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Earth Boost 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":4},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Earth Boost 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":6},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Ragnarok":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":5, "spd":5},
		"fury":5,
		"condition":{"type":"echo"},
	},
	"Distant Def 1":{
		"slot":"a",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":2, "res":2},
		"condition":{"type":"rangeddef"},
	},
	"Distant Def 2":{
		"slot":"a",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":4, "res":4},
		"condition":{"type":"rangeddef"},
	},
	"Distant Def 3":{
		"slot":"a",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":6, "res":6},
		"condition":{"type":"rangeddef"},
	},
	"Wrathful Staff 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"staff",
		"affectsduel":1,
		"wrath":1,
		"condition":{"type":"hpstartmin", "value":1},
	},
	"Wrathful Staff 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"staff",
		"affectsduel":1,
		"wrath":1,
		"condition":{"type":"hpstartmin", "value":.5},
	},
	"Wrathful Staff 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"wrath":1,
		"condition":{"type":"hpstartmin", "value":0},
	},
	"Blarowl":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"Blarowl+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"B Tome Exp. 1":{
		"slot":"c",
		"sp":50,
		"inheritrule":"bluetome",
	},
	"B Tome Exp. 2":{
		"slot":"c",
		"sp":100,
		"inheritrule":"bluetome",
	},
	"B Tome Exp. 3":{
		"slot":"c",
		"sp":200,
		"inheritrule":"bluetome",
		"ismax":1,
	},
	"Regal Blade":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":2, "spd":2},
		"condition":{"type":"chivalry", "value":1},
	},
	"Blessed Bouquet":{
		"slot":"weapon",
		"sp":200,
		"atk":9,
		"inheritrule":"bluetome",
		"affectsduel":1,
	},
	"Blessed Bouquet+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
	},
	"Attack Res 1":{
		"slot":"a",
		"sp":80,
		"atk":1,
		"res":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"Attack Res 2":{
		"slot":"a",
		"sp":160,
		"atk":2,
		"res":2,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Gradivus":{
		"slot":"weapon",
		"sp":400,
		"atk":16,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"anyrangecounter":1,
	},
	"Grani's Shield":{
		"slot":"a",
		"sp":200,
		"inheritrule":"cavalry",
		"affectsduel":1,
		"ismax":1,
		"shield":1,
	},
	"First Bite":{
		"slot":"weapon",
		"sp":200,
		"atk":10,
		"inheritrule":"lance",
		"affectsduel":1,
	},
	"First Bite+":{
		"slot":"weapon",
		"sp":300,
		"atk":14,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
	},
	"Wind Boost 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"spd":2},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Wind Boost 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"spd":4},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Wind Boost 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"spd":6},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Cupid Arrow":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Cupid Arrow+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Candlelight":{
		"slot":"weapon",
		"sp":150,
		"atk":7,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"seal":{"blind":1},
	},
	"Dazzling Staff 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"staff",
		"affectsduel":1,
		"noenemycounter":1,
		"condition":{"type":"hpmin", "value":1},
	},
	"Dazzling Staff 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"staff",
		"affectsduel":1,
		"noenemycounter":1,
		"condition":{"type":"hpmin", "value":.5},
	},
	"Dazzling Staff 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"staff",
		"affectsduel":1,
		"ismax":1,
		"noenemycounter":1,
	},
	"Fortify Res 1 (Seal)":{
		"slot":"s",
		"sp":0,
		"inheritrule":"",
		"ismax":1,
	},
	"Spur Def 1 (Seal)":{
		"slot":"s",
		"sp":0,
		"inheritrule":"",
		"ismax":1,
	},
	"Quickened Pulse":{
		"slot":"s",
		"sp":0,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"precharge":1
	},
	"Breath of Life 1 (Seal)":{
		"slot":"s",
		"sp":0,
		"inheritrule":"",
		"ismax":1,
	},
	"Raudrowl":{
		"slot":"weapon",
		"sp":200,
		"atk":6,
		"inheritrule":"redtome",
		"affectsduel":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"Raudrowl+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
		"condition":{
			"type":"adjacency",
			"effect":"spur", 
			"each":{"atk":2, "spd":2, "def":2, "res":2},
		},
	},
	"Atk Ploy 1":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"atk":-3},
	},
	"Atk Ploy 2":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"atk":-4},
	},
	"Atk Ploy 3":{
		"slot":"c",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"atk":-5},
	},
	"Sturdy Blow 1":{
		"slot":"a",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"atk":2, "def":2},
		"condition":{"type":"init"},
	},
	"Sturdy Blow 2":{
		"slot":"a",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":4, "def":4},
		"condition":{"type":"init"},
	},
	"Sword Exp. 1":{
		"slot":"c",
		"sp":30,
		"inheritrule":"sword",
	},
	"Sword Exp. 2":{
		"slot":"c",
		"sp":60,
		"inheritrule":"sword",
	},
	"Sword Exp. 3":{
		"slot":"c",
		"sp":120,
		"inheritrule":"sword",
		"ismax":1,
	},
	"Firesweep Lance":{
		"slot":"weapon",
		"sp":200,
		"atk":11,
		"inheritrule":"lance",
		"affectsduel":1,
		"noselfcounter":1,
		"noenemycounter":1,
	},
	"Firesweep Lance+":{
		"slot":"weapon",
		"sp":300,
		"atk":15,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"noselfcounter":1,
		"noenemycounter":1,
	},
	"Drive Def 1":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
	},
	"Drive Def 2":{
		"slot":"c",
		"sp":240,
		"inheritrule":"nonstaff",
		"ismax":1,
	},
	"Fire Boost 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"atk":2},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Fire Boost 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"atk":4},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Fire Boost 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":6},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Panic Ploy 1":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"hp", "margin":5},
		"ploy":{"panic":1},
	},
	"Panic Ploy 2":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
		"ploy":{"panic":1},
	},
	"Panic Ploy 3":{
		"slot":"c",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"condition":{"type":"statcomp", "stat":"hp", "margin":1},
		"ploy":{"panic":1},
	},
	"Legion's Axe":{
		"slot":"weapon",
		"sp":200,
		"atk":10,
		"inheritrule":"axe",
		"affectsduel":1,
		"seal":{"panic":1},
	},
	"Legion's Axe+":{
		"slot":"weapon",
		"sp":300,
		"atk":14,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"seal":{"panic":1},
	},
	"Clarisse's Bow":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"bow",
		"affectsduel":1,
		"effective":"flying",
	},
	"Clarisse's Bow+":{
		"slot":"weapon",
		"sp":300,
		"atk":11,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"effective":"flying",
	},
	"Seashell":{
		"slot":"weapon",
		"sp":200,
		"atk":7,
		"inheritrule":"dagger",
		"affectsduel":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"seal":{"def":-5, "res":-5},
		"condition":{"type":"echo"},
	},
	"Seashell+":{
		"slot":"weapon",
		"sp":300,
		"atk":10,
		"inheritrule":"dagger",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"seal":{"def":-7, "res":-7},
		"condition":{"type":"echo"},
	},
	"Seal Atk Spd 1":{
		"slot":"b",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"seal":{"atk":-3, "spd":-3},
	},
	"Seal Atk Spd 2":{
		"slot":"b",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"seal":{"atk":-5, "spd":-5},
	},
	"Refreshing Bolt":{
		"slot":"weapon",
		"sp":200,
		"atk":8,
		"inheritrule":"bow",
		"affectsduel":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
		"effective":"flying",
	},
	"Refreshing Bolt+":{
		"slot":"weapon",
		"sp":300,
		"atk":12,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
		"effective":"flying",
	},
	"Def Ploy 1":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"def":-3},
	},
	"Def Ploy 2":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"def":-4},
	},
	"Def Ploy 3":{
		"slot":"c",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"def":-5},
	},
	"Deft Harpoon":{
		"slot":"weapon",
		"sp":200,
		"atk":10,
		"inheritrule":"lance",
		"affectsduel":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
	},
	"Deft Harpoon+":{
		"slot":"weapon",
		"sp":300,
		"atk":14,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
	},
	"Lance Valor 1":{
		"slot":"c",
		"sp":30,
		"inheritrule":"lance",
	},
	"Lance Valor 2":{
		"slot":"c",
		"sp":60,
		"inheritrule":"lance",
	},
	"Lance Valor 3":{
		"slot":"c",
		"sp":120,
		"inheritrule":"lance",
		"ismax":1,
	},
	"Melon Crusher":{
		"slot":"weapon",
		"sp":200,
		"atk":10,
		"inheritrule":"axe",
		"affectsduel":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
	},
	"Melon Crusher+":{
		"slot":"weapon",
		"sp":300,
		"atk":14,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":2, "spd":2, "def":2, "res":2},
		"fury":2,
		"condition":{"type":"echo"},
	},
	"HP Def 1":{
		"slot":"a",
		"sp":80,
		"hp":3,
		"def":1,
		"inheritrule":"",
		"affectsduel":1,
	},
	"HP Def 2":{
		"slot":"a",
		"sp":160,
		"hp":4,
		"def":2,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
	},
	"Close Def 1":{
		"slot":"a",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":2, "res":2},
		"condition":{"type":"meleedef"},
	},
	"Close Def 2":{
		"slot":"a",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"def":4, "res":4},
		"condition":{"type":"meleedef"},
	},
	"Close Def 3":{
		"slot":"a",
		"sp":240,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"def":6, "res":6},
		"condition":{"type":"meleedef"},
	},
	"Axe Valor 1":{
		"slot":"c",
		"sp":30,
		"inheritrule":"",
	},
	"Axe Valor 2":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
	},
	"Axe Valor 3":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
		"ismax":1,
	},
	"Dark Excalibur":{
		"slot":"weapon",
		"sp":400,
		"atk":14,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"specialboost":10,
	},
	"Mirror Strike 1":{
		"slot":"a",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"atk":2, "res":2},
		"condition":{"type":"init"},
	},
	"Mirror Strike 2":{
		"slot":"a",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"atk":4, "res":4},
		"condition":{"type":"init"},
	},
	"Res Ploy 1":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"res":-3},
	},
	"Res Ploy 2":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
		"affectsduel":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"res":-4},
	},
	"Res Ploy 3":{
		"slot":"c",
		"sp":60,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"condition":{"type":"statcomp", "stat":"res", "margin":1},
		"ploy":{"res":-5},
	},
	"HP Spd 1":{
		"slot":"a",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"hp":3,
		"spd":1,
	},
	"HP Spd 2":{
		"slot":"a",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"hp":4,
		"spd":2,
	},
	"Slaying Edge":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"sword",
		"affectsduel":1,
		"atk":10,
		"charge":1,
	},
	"Slaying Edge+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
		"charge":1,
	},
	"Shield Pulse 1":{
		"slot":"b",
		"sp":60,
		"inheritrule":"melee,infantry,armored",
		"rulestomatch":2,
		"affectsduel":1,
		"precharge":1,
		"condition":{"type":"defensivespecial"},
	},
	"Shield Pulse 2":{
		"slot":"b",
		"sp":120,
		"inheritrule":"melee,infantry,armored",
		"rulestomatch":2,
		"affectsduel":1,
		"precharge":1,
		"specialshield":5,
		"condition":{"type":"defensivespecial"},
	},
	"Shield Pulse 3":{
		"slot":"b",
		"sp":240,
		"inheritrule":"melee,infantry,armored",
		"rulestomatch":2,
		"affectsduel":1,
		"ismax":1,
		"precharge":2,
		"specialshield":5,
		"condition":{"type":"defensivespecial"},
	},
	"Ridersbane":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"lance",
		"affectsduel":1,
		"atk":10,
		"effective":"cavalry",
	},
	"Ridersbane+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
		"effective":"cavalry",
	},
	"Cancel Affinity 1":{
		"slot":"b",
		"sp":50,
		"inheritrule":"melee,physical",
		"rulestomatch":1,
		"affectsduel":1,
		"negateenemyaffinity":1,
		"negateselfaffinity":1,
		"negateenemydisaffinity":1,
	},
	"Cancel Affinity 2":{
		"slot":"b",
		"sp":100,
		"inheritrule":"melee,physical",
		"rulestomatch":1,
		"affectsduel":1,
		"negateenemyaffinity":1,
		"negateselfaffinity":1,
	},
	"Cancel Affinity 3":{
		"slot":"b",
		"sp":200,
		"inheritrule":"melee,physical",
		"rulestomatch":1,
		"affectsduel":1,
		"ismax":1,
		"reverseenemyaffinity":1,
		"negateselfaffinity":1,
	},
	"Slaying Bow":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"bow",
		"affectsduel":1,
		"atk":8,
		"effective":"flying",
		"charge":1,
	},
	"Slaying Bow+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"bow",
		"affectsduel":1,
		"ismax":1,
		"atk":12,
		"effective":"flying",
		"charge":1,
	},
	"Zanbato":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"sword",
		"affectsduel":1,
		"atk":10,
		"effective":"cavalry",
	},
	"Zanbato+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"sword",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
		"effective":"cavalry",
	},
	"Sword Valor 1":{
		"slot":"c",
		"sp":30,
		"inheritrule":"sword",
	},
	"Sword Valor 2":{
		"slot":"c",
		"sp":60,
		"inheritrule":"sword",
	},
	"Sword Valor 3":{
		"slot":"c",
		"sp":120,
		"inheritrule":"sword",
		"ismax":1,
	},
	"Dark Aura":{
		"slot":"weapon",
		"sp":400,
		"inheritrule":"unique",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
	},
	"Drive Atk 1":{
		"slot":"c",
		"sp":120,
		"inheritrule":"",
	},
	"Drive Atk 2":{
		"slot":"c",
		"sp":240,
		"inheritrule":"",
		"ismax":1,
	},
	"Berkut's Lance":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"lance",
		"affectsduel":1,
		"atk":10,
		"spur":{"res":4},
		"condition":{"type":"def"},
	},
	"Berkut's Lance+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"lance",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
		"spur":{"res":4},
		"condition":{"type":"def"},
	},
	"Water Boost 1":{
		"slot":"a",
		"sp":50,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"res":2},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Water Boost 2":{
		"slot":"a",
		"sp":100,
		"inheritrule":"",
		"affectsduel":1,
		"spur":{"res":4},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Water Boost 3":{
		"slot":"a",
		"sp":200,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spur":{"res":6},
		"condition":{"type":"statcomp", "stat":"hp", "margin":3},
	},
	"Lilith Floatie":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"axe",
		"affectsduel":1,
		"atk":10,
	},
	"Lilith Floatie+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"axe",
		"affectsduel":1,
		"ismax":1,
		"atk":14,
	},
	"Infantry Pulse 1":{
		"slot":"c",
		"sp":60,
		"inheritrule":"infantry",
	},
	"Infantry Pulse 2":{
		"slot":"c",
		"sp":120,
		"inheritrule":"infantry",
	},
	"Infantry Pulse 3":{
		"slot":"c",
		"sp":240,
		"inheritrule":"infantry",
		"ismax":1,
	},
	"Tomato Tome":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"redtome",
		"affectsduel":1,
		"atk":8,
	},
	"Tomato Tome+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"redtome",
		"affectsduel":1,
		"ismax":1,
		"atk":12,
	},
	"Hibiscus Tome":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"greentome",
		"affectsduel":1,
		"atk":8,
	},
	"Hibiscus Tome+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"greentome",
		"affectsduel":1,
		"ismax":1,
		"atk":12,
	},
	"Spd Res 1":{
		"slot":"a",
		"sp":80,
		"inheritrule":"",
		"affectsduel":1,
		"spd":1,
		"res":1,
	},
	"Spd Res 2":{
		"slot":"a",
		"sp":160,
		"inheritrule":"",
		"affectsduel":1,
		"ismax":1,
		"spd":2,
		"res":2,
	},
	"G Tome Valor 1":{
		"slot":"c",
		"sp":30,
		"inheritrule":"greentome",
	},
	"G Tome Valor 2":{
		"slot":"c",
		"sp":60,
		"inheritrule":"greentome",
	},
	"G Tome Valor 3":{
		"slot":"c",
		"sp":120,
		"inheritrule":"greentome",
		"ismax":1,
	},
	"Sealife Tome":{
		"slot":"weapon",
		"sp":200,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"atk":8,
	},
	"Sealife Tome+":{
		"slot":"weapon",
		"sp":300,
		"inheritrule":"bluetome",
		"affectsduel":1,
		"ismax":1,
		"atk":12,
	},
	"Swift Strike 1":{
		"slot":"a",
		"sp":120,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"spur":{"spd":2, "res":2},
		"condition":{"type":"init"},
	},
	"Swift Strike 2":{
		"slot":"a",
		"sp":240,
		"inheritrule":"nonstaff",
		"affectsduel":1,
		"ismax":1,
		"spur":{"spd":4, "res":4},
		"condition":{"type":"init"},
	},
}